### ISSUE TITLE
.suo files

### ISSUE THREAD

**Issue by kcris** [QxOrm/QxOrm#1]
Don't store .suo project files under source control, these are temporary user files created when .vsproj is opened

https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/solution-user-options-dot-suo-file?view=vs-2017

Created a PR too.

Thanks for the great work you do.

**Comment by QxOrm** [comment]
Thx I will remove *.suo files in the next check-in...

**Comment by QxOrm** [comment]
Done in this check-in : https://github.com/QxOrm/QxOrm/commit/463d9ee92a1710aabfd80f40e6346b996ba9b32f

**Comment by kcris** [comment]
you're welcome. Note that you can directly merge PRs (if they seem ok, of course), you don't have to redo the commits (this one was trivial, so it was easy to redo it, but you can accept contributions by merging the PR commits into your repo, is how contributions work). Probably you know all that :)
Thanks for your great work on qxorm!
