### ISSUE TITLE
Getting "relation key" data as a string when using fetch_all() without relation [New Feature ?]

### ISSUE THREAD

**Issue by Aditya-Tolikar** [QxOrm/QxOrm#107]
Consider the following example code:
```H
class QX_DLL_EXPORT_HELPER ootpataang
{
public:
	QString m_id{};
	int m_a{};
	QString m_bc{};
	double m_def{};

	ootpataang(){};
	virtual ~ootpataang(){};
};

typedef QSharedPointer<ootpataang> ptrOotpataang;

QX_REGISTER_PRIMARY_KEY(ootpataang, QString)
QX_REGISTER_HPP_EXPORT_DLL (ootpataang, qx::trait::no_base_class_defined, 0)

class QX_DLL_EXPORT_HELPER anotherClass
{
public:
	QString m_id;
	QString m_OP_ID;
	ptrOotpataang m_OP_Obj;

	anotherClass(){};
	virtual ~anotherClass(){};
};

QX_REGISTER_PRIMARY_KEY(anotherClass, QString);
QX_REGISTER_HPP_EXPORT_DLL (anotherClass, qx::trait::no_base_class_defined, 0)
```
```C++
QX_REGISTER_CPP_EXPORT_DLL(ootpataang)
QX_REGISTER_CPP_EXPORT_DLL(anotherClass)

namespace qx
{
	template <> void register_class(QxClass<ootpataang> & t)
	{
		t.id(& ootpataang::m_id, "_id");
	
		t.data(& ootpataang::m_a, "a");
		t.data(& ootpataang::m_bc, "bc");
		t.data(& ootpataang::m_def, "def");
	}

	template <> void register_class(QxClass<anotherClass> & t)
	{
		t.id (&anotherClass::m_id, "_id");
	
		// Either this one Case 1
		t.data(&anotherClass::m_OP_ID, "OP");
		// Or this one Case 2
		t.relationOneToOne(&anotherClass::m_OP_Obj, "OP");
	}
}

```

```C++
void main ()
{
	anotherClass svar, rvar;
	qx::dao::fetch_all(svar);
	qDebug () << qx::serialization::json::to_string(svar);

	qx::dao::fetch_all_with_all_relation(rvar);
	qDebug () << qx::serialization::json::to_string(rvar);
}
```
Currently we can only set a single variable to a key (`"OP"` in this case), so we would only be registering either `m_OP_ID` or `m_OP_Obj`.
In case we register `m_OP_Obj` (Case 2), we can get the object using `fetch_all_with_relation()`, but `fetch_all()` will give a null value.
In case we register `m_OP_ID` (Case 1), we can get `ObjectID` (`QString` in case of `MONGODB`), but using `fetch_all_with_relation()` will not give the related object because we haven't registered it.

The only way I see around this is to make 2 separate fields in the database having the same value:
```C++
t.data(&anotherClass::m_OP_ID, "OP_ID");
t.relationOneToOne(&anotherClass::m_OP_Obj, "OP_OBJECT");
```
But that doesn't really feel good to look at.

**QUESTION:** Does a way currently exist to get the `ObjectID` of the key that has been set as a `relation` when calling the function `fetch_all()` without relation?

**IF NOT:** I would like to suggest one of the following ways to make this feature:
Add a way to dynamically change the registered member
Something like:
```C++
IxClass::replaceDataMember("OP", &anotherClass::m_OP_ID /*Previously registered Data member*/, &anotherClass::m_OP_Obj/*Newly registered data member*/, QxClass<anotherClass>::relationOneToOne /*Method for newly registered data member*/);
```
... which can be used to change from string to relation and later back to the string.
**OR**
Perhaps we can add an option to `relationOneToOne` such that, in case `fetch_all` is called instead of `fetch_all_with_relation`, it would write the object ID to another data member like:
```C++
t.relationOneToOne(&anotherClass::m_OP_Obj, "OP_OBJECT", ... /*Other Arguments*/, &anotherClass::m_OP_ID /*Alternative Data Member*/);
```
NOTE: This is going by the fact that we store relations in MONGO DB as `ObjectID` of the target object and it may be useful for anyone wanting to query by `ObjectID` at a later time.

**Comment by QxOrm** [comment]
Hello,
I don't understand why you don't want to call fetch_all_with_relation() each time to get your relationship instead of fetch_all().
I'm sorry, I think I have not understood your issue.

**Comment by Aditya-Tolikar** [comment]
Suppose we have document A (and we consider it large) in the database:
```JSON
{
	"_id" : ObjectId("..."),
	"field1" : "data1",
	"field2" : "data2",
	"field3" : "data3",
	...
	"otherObject1Id" : ObjectId("..."),
	"otherObject2Id" : ObjectId("..."),
	"otherObject3Id" : ObjectId("..."),
	...
}
```
Now let's say we make a UI that shows all the data fields from this object, with all the `"otherObject#Id"` fields as links to other pages.
If all the other objects are also large documents, you won't want to get all of the data from the relation when the user hasn't asked for it.
Then when the user clicks one of the links some time later, you can fetch the other Document from the database using the `ObjectId ` string that you have.

In this case, you **won't need** to have a `relationOneToOne` and you can simply do...
```C++
class A
{
public:
	QString m_id;
	QString m_field1;
	QString m_field2;
	QString m_field3;
	//	...
	
	QString m_otherObject1Id;
	QString m_otherObject2Id;
	QString m_otherObject3Id;
	//	...
}
A mainDoc;
```
And later you may use something like `fetch_by_id (otherObj, mainDoc.m_otherObject1Id, ...)`.
This way, it will greatly reduce the load on the MONGODB server (which takes more clock cycles if it has to process a `lookup` in case of fetching by relation) and the network load.

But if you want the ability to use `fetch_all_with_relation()` you need to first set `relationOneToOne(...)` which would also require `m_otherObject#Id` (which could instead be `m_otherObject#Ptr`) to be of the corresponding type.

**Comment by Aditya-Tolikar** [comment]
On top of this, it might also be useful to be able to get Object Id of any of the objects you didn't ask for the relation to.
For example...
If we ask for `fetch_all_with_relation` and select the fields `otherObject1Ptr` and `otherObject2Ptr` but don't select the field `otherObject3Ptr` and other fields that have a relation.
In that case, it would be useful to be able to get the `ObjectId` in `QString m_otherObject3Id`  and other `m_otherObject#Id` which were not asked for in the relation.

**Comment by QxOrm** [comment]
Ok, thx for the explanation.
For classics SGBD (Oracle, MSSQLServer, PostgreSQL, MySQL, SQLite, etc...), there is a mechanism of "lazy loading" (which gets only the ID of a relation) for relationships n-1 and 1-1.
So, if I understand well, you mean that "lazy loading" doen't work with MongoDB (this is possible, I don't remember).

Be careful with "relationOneToOne", I think in your case, you should use "RelationManyToOne" (relationOneToOne should be used only if several items share exactly the same ID).

If you don't want to load all data of a relationship, you can select the relation to fetch + the properties in the relation to fetch, which can reduce the load.
You have some examples in the project sample : [https://github.com/QxOrm/QxOrm/tree/master/test/qxBlogMongoDB](https://github.com/QxOrm/QxOrm/tree/master/test/qxBlogMongoDB)

In the following example, you fetch only : the _blog_text_ property of _blog_ instance + _author_ _name_ and its _ID_ for each _author_ relationship : 
```
   list_blog lstBlogComplexRelation;
   daoError = qx::dao::fetch_all_with_relation(QStringList() << "{ blog_text }" << "author_id { name }", lstBlogComplexRelation);
   qAssert(! daoError.isValid());
   qx::dump(lstBlogComplexRelation);
```

**Comment by Aditya-Tolikar** [comment]
> Be careful with "relationOneToOne", I think in your case, you should use "RelationManyToOne" (relationOneToOne should be used only if several items share exactly the same ID).

Thanks for that, I'll check out exactly which type of relation I want to use.

> relation to fetch + the properties in the relation to fetch, which can reduce the load

I get that part, and as I stated in [the next comment](https://github.com/QxOrm/QxOrm/issues/107#issuecomment-1742571994)

1. If I choose to have data from only some of the relations, the data for the rest of them will be void in the C++ class object.
2. If I choose to get only the Object Id from the related target document, it will still be internally using a `lookup`. So even if the network load were to be reduced, the number of extra processing steps the MONGODB server will be taking would still be the same.
On the other hand, since the object Id of the target is already stored directly in the same document in the database, it would be much faster for the MONGODB server to just return only that object (and only relations that we asked for, but oid strings for the relations we didn't ask for) and QxOrm could do the rest as it does currently (just be selectable during runtime, which data goes where).

**Comment by Aditya-Tolikar** [comment]
Thanks for your reply.

> setDao(false)

That helps, but only partially, since it doesn't change the fact that I will be making 2 entries in the Database, "OP" and "OP_ID".
If I were to make 2 separate entries having the same data, I could simply use the options in `fetch_by_query` and `fetch_.._with_relation` of selecting only the fields that I want returned, to get the result without needing `setDao(false)`.

On the other hand, if I could get something like:
```C++
qx::QxClassX::getDataMember("anotherClass", "OP_ID")->setKey("OP");
// OR
qx::QxClassX::getDataMember("anotherClass", "OP_ID")->setFieldName("OP");
```
which I could use to change to the Key in the Database...
_______________________
I actually just found something similar looking (thanks to your previous suggestion) : 
`void qx::IxDataMember::setName(const QString & s);`, which seems usable in this way:

```C++
// ... register_class (...)
{
	t.data (&anotherClass::m_OP_ID, "OP_ID");
	t.relationOneToOne (&anotherClass::m_OP_Obj, "OP_Obj");
}
```
While using it, I might be able to (considering database has the key "OP_ID")
```C++
void function_get_with_relation (/*...*/)
{
	// Use some mutex with anotherClass to make sure other threads don't access it when I have changed member names
	qx::QxClassX::getDataMember("anotherClass", "OP_ID").setName("OP_TempUnused");
	qx::QxClassX::getDataMember("anotherClass", "OP_Obj").setName("OP_ID");
	// fetch with OP_ID as relation
	// ...
	// the anotherClass object can now be used elsewhere
	// --------
	qx::QxClassX::getDataMember("anotherClass", "OP_ID").setName("OP_Obj");
	qx::QxClassX::getDataMember("anotherClass", "OP_TempUnused").setName("OP_ID"); 
	// Unlock mutex
}
void function_get_without_relation (/*...*/)
{
	// Directly call qx::dao::fetch_by_query
	// Because the Object Id field is already mapped to a QString beforehand
}
```
I will try this out and report in this thread, unless the `setName()` is for something else and I am mistaken.

**Comment by Aditya-Tolikar** [comment]
The best way would be if the following query could be auto-generated.

```JSON
[ 
	{ "$lookup": { 
		"from": "location", 
		"let": { "locationObj": "$location" }, 
		"pipeline": [ { "$match": { "$expr": { "$eq": [ "$_id", "$$locationObj" ] } } }   ], 
		"as": "locationObj" } },
	{ "$addFields": { "locationObj": { "$arrayElemAt": [ "$locationObj", 0 ] } } } ]
```

Notice the `$locationObj` in the `"let"` key has been changed to `"location"`.
```JSON mongosh
{
        "_id" : ObjectId("6536c01354220f924a0d48d1"),
        "location" : ObjectId("6536c01354220f924a0d48d2"),
        "locationObj" : {
                "_id" : ObjectId("6536c01354220f924a0d48d2"),
                "x" : 10,
                "y" : 20
        },
        "name" : "sprite1"
}
```

This way the result will already be matching the class and no change would be required in the serialisation step.
Is there any method to register such a relation?

**Comment by QxOrm** [comment]
Hello,

So if I understand well, you would want to : 

- instead of what is generated for now by QxOrm library : 
```
	{ "$lookup": { 
		"from": "location", 
		"let": { "locationObj": "$locationObj" }, 
		"pipeline": [ { "$match": { "$expr": { "$eq": [ "$_id", "$$locationObj" ] } } }   ], 
		"as": "locationObj" } },
	{ "$addFields": { "locationObj": { "$arrayElemAt": [ "$locationObj", 0 ] } } } ]
```

- you would expect/prefer : 
```
	{ "$lookup": { 
		"from": "location", 
		"let": { "locationObj": "$location" }, 
		"pipeline": [ { "$match": { "$expr": { "$eq": [ "$_id", "$$locationObj" ] } } }   ], 
		"as": "locationObj" } },
	{ "$addFields": { "locationObj": { "$arrayElemAt": [ "$locationObj", 0 ] } } } ]
```

The only diff is in the "let" part.

I checked the code and I think it should be easy to provide this new feature.
We could create a new method to use in the qx::register_class<T> function, something like : 
```
   qx::IxDataMember * pDataRelationKey = t.data(&citizen::locationOid, "location");
   IxSqlRelation * pRelation = t.relationOneToOne(&citizen::locationObj, "locationObj");
   pRelation->linkRelationKeyTo(pDataRelationKey);
```

If you have a better function name than "linkRelationKeyTo", please let me know.

Then, in the QxMongoDB_Helper.cpp file, method buildLookup(), it should be easy to write : 
```
   else if (type == qx::IxSqlRelation::one_to_one)
   {
      lookup.replace("%COLL_LET_KEY%", pDataMember->getKey());
      lookup.replace("%COLL_LET_VAL%", (pRelation->getLinkRelationKey() ? pRelation->getLinkRelationKey() : pDataMember->getKey());
      lookup.replace("%COLL_EQ%", "_id");
   }
```
And the same thing for (type == qx::IxSqlRelation::many_to_one).

What do you think about that ?

**Comment by QxOrm** [comment]
Please download the latest version, you can now write something like this in the **qx::register_class** function : 
```
   qx::IxDataMember * pDataRelationKey = t.data(&citizen::locationOid, "location");
   qx::IxSqlRelation * pRelation = t.relationOneToOne(&citizen::locationObj, "locationObj");
   pRelation->linkRelationKeyTo(pDataRelationKey);
```
Please note that I have not tested it, just run the regressions tests.

**Comment by Aditya-Tolikar** [comment]
Thanks a lot.
I tried out the changes in my test case and it works.
qxBlogMongoDB test passed.
I had some problem with the linker when making qxBlogRestApi probably because I chose some wrong options when rebuilding QxOrm, so I will try it properly tomorrow.
