### ISSUE TITLE
c++ preview is empty if the "Custom" inheritance is selected.

### ISSUE THREAD

**Issue by wxwok** [QxOrm/QxOrm#115]
* Create an entity and open the C++ preview tab at the right.
** If I select the "No inheritance"/"qx::IxPersistable"/"qx::IxPersistable+QObject, it shows the generated C++ code.
** If I select "Custom",  it shows nothing in the Header(.h) or the Source(.cpp) tabs.

* I also want to know how to create the base class if the "Custom" inheritance works.

![1](https://github.com/QxOrm/QxOrm/assets/561843/4e9afd6c-addf-4ce1-bc02-dd54c80b4e3b)

![2](https://github.com/QxOrm/QxOrm/assets/561843/76962093-5c25-4bca-8abd-31f917105679)
![Screenshot from 2023-12-10 22-14-45](https://github.com/QxOrm/QxOrm/assets/561843/272061d1-0a5d-47a8-8b60-e26228708280)
![Screenshot from 2023-12-10 22-15-07](https://github.com/QxOrm/QxOrm/assets/561843/829eb59b-5131-4168-945d-8f26e374559a)

**Comment by QxOrm** [comment]
Hello,
To define custom C++ export .h/.cpp : from the main menu of QxEntityEditor : Tools >> Export to C++ project (settings).
https://www.qxorm.com/qxorm_en/manual_qxee.html#cpp_export_settings_parameters
Then you can select Custom and put your C++ code here.

For other customizations like base classe, you can use the Javascript engine integrated in QxEntityEditor.
Documentation here : https://www.qxorm.com/qxorm_en/manual_qxee.html#js_engine

**Comment by wxwok** [comment]
Thank you.
