### ISSUE TITLE
Best use of custom classes generated by QxOrmEditor

### ISSUE THREAD

**Issue by abuhles** [QxOrm/QxOrm#120]
I am still trying to make the best out of the c++ viewmodel class. But i don't get what the custom classes are good for. Is there a way to use them to add methods to the viewmodel classes? 
Can i get some examples for how to make them work in my favor?

**Comment by QxOrm** [comment]
Hello,
Here is the documentation about these custom classes : 
`Field « Generate a custom directory with custom files for each entity » : if enabled, generated C++ project contains a custom file per entity. By default, these custom files are empty and will never be removed or erased by another export. These custom files can be used for example to implement [validation methods](https://www.qxorm.com/qxorm_en/manual.html#manual_420), or [trigger functions](https://www.qxorm.com/qxorm_en/manual.html#manual_410).`
