### ISSUE TITLE
How to efficiently determine whether a table exists？

### ISSUE THREAD

**Issue by qht1003077897** [QxOrm/QxOrm#126]
How to efficiently determine whether a table exists? I am currently using the following method, but it is too slow。

```
bool SqlHelper::isExistTable(const QString& tableName)
{
    QStringList tables = qx::QxSqlDatabase::getSingleton()->getDatabase().tables();
    return tables.contains(tableName, Qt::CaseInsensitive);
}
```

My requirement is that I want to check whether the table exists before creating the table, and if the table exists, I do not create it. If I don't, I get an error:
> Database error number '1' : 
Unable to execute statement
table KeyModel already exists

**Comment by QxOrm** [comment]
Hello,

I think you are using the right method : QSqlDatabase::tables().

If it is too slow, maybe you could create your own C++ cache if you don't need to check at database level each time.
Or maybe you could call a specific and faster SQL query to get this information (depending on your SGBD).

**Comment by qht1003077897** [comment]
Okay, I see,the cache might be a relatively good way to do it
