### ISSUE TITLE
Exporting/Importing enum constant to JSON from Model classes

### ISSUE THREAD

**Issue by abuhles** [QxOrm/QxOrm#128]
I got QxEditor generated model classes with enum properties. Using to_json will convert these into integer values. Can you give me a good way to export the enum constant instead of the integer, please?

**Comment by QxOrm** [comment]
Hello,
Not sure to understand exactly your issue.
A new version of QxEntityEditor will be released soon with 2 new plugins named : **QxEESourceControlExport** / **QxEESourceControlImport**.

Enumerations are managed by these plugins, and the result looks like this : 
```
{
    "key": "sex",
    "dt_creation": "20131206221840",
    "dt_modification": "20131210205552",
    "name": "sex",
    "namespace": "",
    "description": "",
    "version": "0",
    "project_version": "0",
    "qt_enum": "false",
    "list_of_key_value": {
        "male": "1",
        "female": "2",
        "unknown": "3"
    }
}
```

So you have both the enum constant names + the enum integer values.

**Comment by abuhles** [comment]
Serialising custom types is the right entry in the manual to use.
