### ISSUE TITLE
MongoDB: fetch_by_id_with_all_relation() returns wrong object

### ISSUE THREAD

**Issue by ChrizzyM87** [QxOrm/QxOrm#13]
Hi, 
first of all: thanks for the great library!
I probably found a bug. Getting myself into the QxOrm library to access a MongoDB database I found out that, qx::dao::fetch_by_id_with_all_relation() returns the wrong object. The object returned seems to be the first object of that kind in the database, but not the one the provided id is referring to.
I debugged and ended up at the file "QxDao_FetchById_WithRelation.inl":
![qxOrm_Bug_1](https://user-images.githubusercontent.com/21241672/69051578-04364080-0a05-11ea-9f8c-6bcb98eab626.png)

![qxOrm_Bug_2](https://user-images.githubusercontent.com/21241672/69051579-04364080-0a05-11ea-96b4-1fe61b3bfd5a.png)

In this example I wanted to fetch the object with id '..de4' but in line 55 somehow the id in the json query is changed to '...de3'.

**Comment by ChrizzyM87** [comment]
Same for qx::dao::fetch_by_id_with_relation()

**Comment by ChrizzyM87** [comment]
My workaround: 
(person->m_id is set)
```
bool MongoDB_Worker::fetchPersonWithRelation(MDB_Person *person) {
    ///workaround:
    QHash<QString, MDB_Person> ret;
    QSqlError daoError = qx::dao::fetch_all_with_relation("*->", ret);
    *person = ret[person->m_id];
    ///@todo wrong person! waiting for bug fix, workaround above
//    QSqlError daoError = qx::dao::fetch_by_id_with_all_relation("*->", person); ///ERROR wrong person
    if (daoError.isValid()) { //isValid() returns true if an error occured
        qWarning() << "MongoDB_Worker::fetchVitalSignsOfPerson(): Error fetching with all relations:" << daoError;
    }

    return !daoError.isValid();
}
```
Of course this workaround is not suitable for large collections.

**Comment by QxOrm** [comment]
Hello,

Thx for using QxOrm library with MongoDB !

Is it possible to reproduce the issue with the qxBlogMongoDB sample project in ./test/ directory of QxOrm package ?
It will be easier for me to debug and fix it if there is a bug.
I checked and the qxBlogMongoDB sample project contains already some calls to : 
- qx::dao::fetch_by_id_with_all_relation()
- qx::dao::fetch_by_id_with_relation()

So if you can modify a bit this sample project to reproduce the issue, it would be great !

**Comment by ChrizzyM87** [comment]
Hello,
thanks for your answer and sorry, that it took a while! I added some code to add a second blog and fetch that one by id, which returns the first blog of the collection. Its the first time I forked a github project and made a pull request. So, if I did anything wrong or can improve something, I appreciate feedback!
Greetings
Christoph

**Comment by QxOrm** [comment]
Hello,
Thx for the sample modifications to reproduce the issue.
And no problem about GitHub process : I'm not an expert with GitHub too, this is not my main source repository, so don't worry :)
I think I have fixed the issue : could you please download latest source code to check ?
Thx !

**Comment by ChrizzyM87** [comment]
Yes!! You fixed it! Thank you very much for your work!
