### ISSUE TITLE
How to serialize array members in a structure，It compiles with an error message

### ISSUE THREAD

**Issue by xiaocai123123** [QxOrm/QxOrm#132]
Hello！
I have a struct like below

Test.h
struct BeginCut
{
   double BeginCutLength[2];
};
QX_REGISER_HPP_EXPORT_DLL(BeginCut, qx::trait::no_base_class_defined, 0)

Test.cpp
QX_REGISER_CPP_EXPORT_DLL(BeginCut)
namespace qx
{
   template<>void register_class(QxClass<BeginCut>& t)
      {
         t.data(&BeginCut::BeginCutLength, "BeginCutLength");
       }
}
    When I compile this struct who has a array member, an error occurs：qx_need_to_specialize_template_conver_to_string_from_string
    How QxOrm supports array data member？
    Sincerely looking forward to your reply

**Comment by QxOrm** [comment]
Hello,

This error qx_need_to_specialize_template_conver_to_string_from_string means that "double [2]" is not a type supported by QxOrm library by default.

You have to write how to convert double [2] to/from QVariant and to/from QJson.
The documentation is here (Persist custom type) : https://www.qxorm.com/qxorm_en/manual.html#manual_460

There is a full example here :
```
#ifndef _MY_CUSTOM_PERSISTABLE_TYPE_H_
#define _MY_CUSTOM_PERSISTABLE_TYPE_H_

#ifdef _MSC_VER
#pragma once
#endif

#include <QxOrm.h>

class MyPersistableType
{
   /* What you want here */
};

QX_REGISTER_CLASS_NAME(MyPersistableType)
QX_CLASS_VERSION(MyPersistableType, 0)

QDataStream & operator<< (QDataStream & stream, const MyPersistableType & t)
{
   /* Your implementation here */
}

QDataStream & operator>> (QDataStream & stream, MyPersistableType & t)
{
   /* Your implementation here */
}

namespace qx {
namespace cvt {
namespace detail {

template <> struct QxConvert_ToVariant< MyPersistableType > {
static inline QVariant toVariant(const MyPersistableType & t, const QString & format, int index, qx::cvt::context::ctx_type ctx)
{
   /* Here I convert from MyPersistableType to QVariant */
} };

template <> struct QxConvert_FromVariant< MyPersistableType > {
static inline qx_bool fromVariant(const QVariant & v, MyPersistableType & t, const QString & format, int index, qx::cvt::context::ctx_type ctx)
{
   /* Here I convert from QVariant to MyPersistableType */
   return qx_bool(true);
} };

} // namespace detail
} // namespace cvt
} // namespace qx

#ifndef _QX_NO_JSON

namespace qx {
namespace cvt {
namespace detail {

template <>
struct QxConvert_ToJson< MyPersistableType >
{
   static inline QJsonValue toJson(const MyPersistableType & t, const QString & format)
   {
      /* Your implementation here */
   }
};

template <>
struct QxConvert_FromJson< MyPersistableType >
{
   static inline qx_bool fromJson(const QJsonValue & j, MyPersistableType & t, const QString & format)
   {
      /* Your implementation here */
   }
};

} // namespace detail
} // namespace cvt
} // namespace qx

#endif // _QX_NO_JSON

// ------------------------------------
// If you are using boost serialization, you have also to implement save/load functions like above 'ExtObject3D' example
// ------------------------------------

#endif // _MY_CUSTOM_PERSISTABLE_TYPE_H_
```
Just replace MyPersistableType by your double array type.

**Comment by xiaocai123123** [comment]
Thanks to your apply!
I just think double [2] likes std::vector or std::array,and i don`t know how to coding with your example --MyPersistableType that i think it`s not convenient to basic data type.
I used librarys like cereal 、ylt （Alibaba） ,they are directly supporting array like double[2] and not need users coding another template functions.Can QxOrm support it

**Comment by QxOrm** [comment]
Hello,

Imagine you want to store your double[2] type as TEXT in your database, have you tried something like this to specialize the template ?

```
template <size_t N>
struct QxConvert_ToVariant< double[N] > {
static inline QVariant toVariant(const double & t[N], const QString & format, int index, qx::cvt::context::ctx_type ctx)
{
   QStringList lst;
   for (size_t i = 0; i++; i < N) {
      lst << QString::number(t[i]);
   }
   QVariant v = lst.join("|");
   return v;
}};

template <size_t N>
struct QxConvert_FromVariant< double[N] > {
static inline qx_bool fromVariant(const QVariant & v, double & t[N], const QString & format, int index, qx::cvt::context::ctx_type ctx)
{
   QString s = v.toString();
   QStringList lst = s.split("|");
   for (size_t i = 0; i++; i < N) {
      t[i] = lst.at(i).toDouble();
   }
   return qx_bool(true);
}};
```

And about JSON, just create a QJsonArray.

**Comment by xiaocai123123** [comment]
> Hello,
> 
> Imagine you want to store your double[2] type as TEXT in your database, have you tried something like this to specialize the template ?
> 
> ```
> template <size_t N>
> struct QxConvert_ToVariant< double[N] > {
> static inline QVariant toVariant(const double & t[N], const QString & format, int index, qx::cvt::context::ctx_type ctx)
> {
>    QStringList lst;
>    for (size_t i = 0; i++; i < N) {
>       lst << QString::number(t[i]);
>    }
>    QVariant v = lst.join("|");
>    return v;
> }};
> 
> template <size_t N>
> struct QxConvert_FromVariant< double[N] > {
> static inline qx_bool fromVariant(const QVariant & v, double & t[N], const QString & format, int index, qx::cvt::context::ctx_type ctx)
> {
>    QString s = v.toString();
>    QStringList lst = s.split("|");
>    for (size_t i = 0; i++; i < N) {
>       t[i] = lst.at(i).toDouble();
>    }
>    return qx_bool(true);
> }};
> ```
> 
> And about JSON, just create a QJsonArray.

It`s awesome!
I learned QxOrm use boost::serialization to serialized or deserialized data with binary or xml.But serialized or deserialized to json,it's must used specialized template like toVariant and fromJson,or it`s compiled error.
Now i finished this problem with your help. thank you so much!
