### ISSUE TITLE
Error: Cannot find the androiddeploy Json file

### ISSUE THREAD

**Issue by ncg81** [QxOrm/QxOrm#14]
Hello,

I want to test QxOrm in order to assess its suitability for my cross-platform project. My test project is set-up as a Qt app template, with QxOrm root folder residing in the project folder and included thus:

`include(QxOrm/QxOrm.pri)`

Please note that my project has multiple dependencies included just as the above `include(Abc/Abc.pri)`, `include(Def/Def.pri)` etc. 

The moment I add QxOrm, I can build the project, but cannot deploy it to Android anymore (works for Windows, Mac and iOS builds, just not Android). 

Qt Creator (4.10.2) bombs with the following error:

```
Cannot find the androiddeploy Json file.
Error while building/deploying project BlahBlah (kit: Android for arm64-v8a (Clang Qt 5.13.2 for Android ARM64-v8a))
When executing step "Deploy to Android device"
```

Now, I found [QTCREATORBUG-15931](https://bugreports.qt.io/browse/QTCREATORBUG-15931) but I am not convinced it is the same case I am facing although the error output is similar, because as mentioned I have multiple third party .pri files included and face no issues until I add QxOrm. Commenting out `include(QxOrm/QxOrm.pri)` leads to succesful deployment again.

Any ideas?

**Comment by QxOrm** [comment]
Hello,

This is maybe a dependency issue.
By default, when you add QxOrm library to your project, you add also these dependencies :
- QtCore
- QtSql
- and the Qt SQL driver which is load at runtime

You can have more dependencies if you change some compilation options in QxOrm.pri configuration file.

On this link : https://forum.qt.io/topic/92741/cannot-find-the-androiddeploy-json-file/3
They talk about a shadow build issue, so you could try to disable shadow build, then rebuild all project.

> It relates to the "shadow build" option in the "Projects" tab within QtCreator. If you un-check the option and run qmake then re-build, it should work just fine.

**Comment by ncg81** [comment]
Fiddling with the shadow build option doesn't change anything. I also attempted to build the library separately for Android hoping that I might be able to link against it instead of including the .pri. 

No joy. Here's what happens (output from Windows build host, same error on Linux & Mac build hosts):

```
15:17:06: Running steps for project QxOrm...
15:17:06: Starting: "C:\Program_Inst\Development\Ide\Qt\5.13.2\android_armv7\bin\qmake.exe" C:\Program_Inst\Development\Pro\Qt\QxOrm\QxOrm.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug"
Info: creating stash file C:\Program_Inst\Development\Pro\Qt\build-QxOrm-Android_for_armeabi_v7a_Clang_Qt_5_13_2_for_Android_ARMv7-Debug\.qmake.stash
15:17:10: The process "C:\Program_Inst\Development\Ide\Qt\5.13.2\android_armv7\bin\qmake.exe" exited normally.
15:17:10: Starting: "C:\Program_Inst\Development\Ide\Google\Android\Sdk\ndk\20.1.5948944\prebuilt\windows-x86_64\bin\make.exe" -f C:/Program_Inst/Development/Pro/Qt/build-QxOrm-Android_for_armeabi_v7a_Clang_Qt_5_13_2_for_Android_ARMv7-Debug/Makefile qmake_all
make: Nothing to be done for `qmake_all'.
15:17:10: The process "C:\Program_Inst\Development\Ide\Google\Android\Sdk\ndk\20.1.5948944\prebuilt\windows-x86_64\bin\make.exe" exited normally.
15:17:10: Starting: "C:\Program_Inst\Development\Ide\Google\Android\Sdk\ndk\20.1.5948944\prebuilt\windows-x86_64\bin\make.exe" -j8
C:/Program_Inst/Development/Ide/Google/Android/Sdk/ndk/20.1.5948944/prebuilt/windows-x86_64/bin/make -f Makefile.Debug
make[1]: Entering directory `C:/Program_Inst/Development/Pro/Qt/build-QxOrm-Android_for_armeabi_v7a_Clang_Qt_5_13_2_for_Android_ARMv7-Debug'
C:\Program_Inst\Development\Ide\Google\Android\Sdk\ndk\20.1.5948944/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++ -D__ANDROID_API__=21 -target armv7-none-linux-androideabi -gcc-toolchain C:\Program_Inst\Development\Ide\Google\Android\Sdk\ndk\20.1.5948944/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 -fno-limit-debug-info -DANDROID_HAS_WSTRING --sysroot=C:\Program_Inst\Development\Ide\Google\Android\Sdk\ndk\20.1.5948944/sysroot -isystem C:\Program_Inst\Development\Ide\Google\Android\Sdk\ndk\20.1.5948944/sysroot/usr/include/arm-linux-androideabi -isystem C:\Program_Inst\Development\Ide\Google\Android\Sdk\ndk\20.1.5948944/sources/cxx-stl/llvm-libc++/include -isystem C:\Program_Inst\Development\Ide\Google\Android\Sdk\ndk\20.1.5948944/sources/android/support/include -isystem C:\Program_Inst\Development\Ide\Google\Android\Sdk\ndk\20.1.5948944/sources/cxx-stl/llvm-libc++abi/include -fstack-protector-strong -DANDROID -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -fno-builtin-memmove -g -g -marm -O0 -Wall -W -D_REENTRANT -fPIC -D_QX_MODE_DEBUG -D_QX_BUILDING_QX_ORM -DQT_QML_DEBUG -DQT_SQL_LIB -DQT_CORE_LIB -I..\QxOrm -I. -I..\QxOrm\include -I..\..\..\Ide\Qt\5.13.2\android_armv7\include -I..\..\..\Ide\Qt\5.13.2\android_armv7\include\QtSql -I..\..\..\Ide\Qt\5.13.2\android_armv7\include\QtCore -Iqt\moc -I..\..\..\Ide\Qt\5.13.2\android_armv7\mkspecs\android-clang -x c++-header -c ..\QxOrm\include\QxPrecompiled.h -o debug\QxOrmd\c++.gch
C:\Program_Inst\Development\Ide\Google\Android\Sdk\ndk\20.1.5948944/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++ -c -include debug\QxOrmd -D__ANDROID_API__=21 -target armv7-none-linux-androideabi -gcc-toolchain C:\Program_Inst\Development\Ide\Google\Android\Sdk\ndk\20.1.5948944/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 -fno-limit-debug-info -DANDROID_HAS_WSTRING --sysroot=C:\Program_Inst\Development\Ide\Google\Android\Sdk\ndk\20.1.5948944/sysroot -isystem C:\Program_Inst\Development\Ide\Google\Android\Sdk\ndk\20.1.5948944/sysroot/usr/include/arm-linux-androideabi -isystem C:\Program_Inst\Development\Ide\Google\Android\Sdk\ndk\20.1.5948944/sources/cxx-stl/llvm-libc++/include -isystem C:\Program_Inst\Development\Ide\Google\Android\Sdk\ndk\20.1.5948944/sources/android/support/include -isystem C:\Program_Inst\Development\Ide\Google\Android\Sdk\ndk\20.1.5948944/sources/cxx-stl/llvm-libc++abi/include -fstack-protector-strong -DANDROID -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -fno-builtin-memmove -g -g -marm -O0 -Wall -W -D_REENTRANT -fPIC -D_QX_MODE_DEBUG -D_QX_BUILDING_QX_ORM -DQT_QML_DEBUG -DQT_SQL_LIB -DQT_CORE_LIB -I..\QxOrm -I. -I..\QxOrm\include -I..\..\..\Ide\Qt\5.13.2\android_armv7\include -I..\..\..\Ide\Qt\5.13.2\android_armv7\include\QtSql -I..\..\..\Ide\Qt\5.13.2\android_armv7\include\QtCore -Iqt\moc -I..\..\..\Ide\Qt\5.13.2\android_armv7\mkspecs\android-clang -o debug\bool_array.obj ..\QxOrm\src\QxMemLeak\bool_array.cpp
<built-in>:1:10: fatal error: 'debug\QxOrmd' file not found
#include "debug\QxOrmd"
         ^~~~~~~~~~~~~~
1 error generated.
make[1]: *** [debug\bool_array.obj] Error 1
make[1]: Leaving directory `C:/Program_Inst/Development/Pro/Qt/build-QxOrm-Android_for_armeabi_v7a_Clang_Qt_5_13_2_for_Android_ARMv7-Debug'
make: *** [debug] Error 2
15:17:13: The process "C:\Program_Inst\Development\Ide\Google\Android\Sdk\ndk\20.1.5948944\prebuilt\windows-x86_64\bin\make.exe" exited with code 2.
Error while building/deploying project QxOrm (kit: Android for armeabi-v7a (Clang Qt 5.13.2 for Android ARMv7))
When executing step "Make"
15:17:13: Elapsed time: 00:06.
```
Summing it up:

a) Windows, Linux, Mac & iOS builds

- Including the QxOrm.pri in my project -> OK
- Building QxOrm separately -> OK

b) Android builds

- Including the .pri in my project and building -> OK (this does not build an APK);
- Including the .pri in my project and deploying -> FAIL (Cannot find the androiddeploy Json file.). Comment out include(QxOrm/QxOrm.pri) and I am able to deploy again;
- Building QxOrm separately -> FAIL (with the error above)

**Comment by QxOrm** [comment]
If you still have issues with Android, here are some things to try :
1- I don't know how to do it, but it should have a way to run qmake with a **verbose mode** ==> then maybe output logs will display what is wrong
2- try to run **androiddeployqt** manually : https://doc.qt.io/qt-5/deployment-android.html
3- your issue really looks like a dependency issue, so I think you could test to build QxOrm in static mode to remove a dependency : just add **_QX_STATIC_BUILD** compilation option in _QxOrm.pri_ configuration file

**Comment by ncg81** [comment]
The issues mentioned only manifest once I include QxOrm. There are no issues with about a dozen other dependencies (*.pri). To me this is a strong hint they are due to QxOrm project structure.

Enough with this nonsense. Closing.
