### ISSUE TITLE
Register getters/setters

### ISSUE THREAD

**Issue by ChrizzyM87** [QxOrm/QxOrm#16]
Hello,
the qxBlogMongoDB example shows how to register a function via `t.fct_0<int>(std::mem_fn(& author::age), "age");`, but is is somehow possible to register different functions for read/write access e.G. getters and setters?
Background is that I need to lock mutexes depending on read/write access.
Best regards
Christoph

**Comment by QxOrm** [comment]
Hello,

You can define your properties as _protected_ or _private_ : then your properties will be accessed only with getters/setters.
But this is true that when QxOrm library performs some database operation, it will access to the property directly without using any getters/setters.

For now, there is a way to define getters/setters for QxOrm library.
Your class must inherit from _Q_OBJECT_, and you have to define your property with _Q_PROPERTY_.
Then in your _qx::register_class<T>()_ function, just write :
`qx::register_all_qt_properties< className >(t, propertyId);`
You have an example in **./test/qxDllSample/dll1/include/TestQtProperty.h** class.

But there is a restriction about _Q_PROPERTY_ : you can't define relationships with that.

I will think about adding something to not have to use _Q_OBJECT_ / _Q_PROPERTY_, but for now it doesn't exist.

**Comment by ChrizzyM87** [comment]
This is **amazing**! Works perfectly! Thank you very much!!!

**Comment by QxOrm** [comment]
Great !
The documentation is here : https://www.qxorm.com/qxorm_en/manual.html#manual_520
