### ISSUE TITLE
Inheritance issues

### ISSUE THREAD

**Issue by ChrizzyM87** [QxOrm/QxOrm#18]
Hello,
sorry, another question came up and I could not find a solution for it.
I have a base class, where attributes m_id and m_tsp are defined. Base class is derived from QObject and attributes are register via Q_PROPERTY and QX_REGISTER_ALL_QT_PROPERTIES makros. I tried to use QX_REGISTER_BASE_CLASS and QX_REGISTER_COMPLEX_CLASS_NAME_HPP / CPP, but when I used these it won't compile, so I removed them.

My derived classes are also using the Q_PROPERTY mechanism to register their attributes. I'm using QX_REGISTER_COMPLEX_CLASS_NAME_HPP / CPP to register class names and QX_REGISTER_PRIMARY_KEY to register the prim. key (which is actually defined in the base class).

This works fine, but I get this output:
`[QxOrm] Unable to define correct class name : 'PN2DB4BaseE' => use macro 'QX_REGISTER_CLASS_NAME()' or 'QX_REGISTER_CLASS_NAME_TEMPLATE_X()'`

What do I have to do to register the base class name?
Second question is: Do I have to call functions like insert() with ptr to the concrete object or is it somehow possible to pass the base class ptr and QxOrm finds out the concrete class?
I tried to pass the base class ptr, but I get an error that says that the base class is not registered (-> first problem)
Thanks a lot!

**Comment by QxOrm** [comment]
Hello,

For your first question : try to design it with QxEntityEditor application ==> you will see in the generated C++ source code how to do.

For your second question : you have to inherit from **qx::IxPersistable**.
The documentation is here : https://www.qxorm.com/qxorm_en/manual.html#manual_450
Again, QxEntityEditor application can help you to know how to write your classes.

**Comment by ChrizzyM87** [comment]
Hello, thanks again for your support! I used QxEntityEditor like you suggested to see how to design classes with persistance and it compiles without errors :)
My setup is a child class "MDB_Person", which inherits from "MDB_Base" and "MDB_Base" inherits from qx::IxPersistable. Unfortunately calling `qx::dao::insert(base_ptr);`, where `base_ptr` is of type `MDB_Base*`, but castable to `MDB_Person*` only inserts the `MDB_Base` object to the database:
``` 
MongoDB insert one 'MDB_Base' :
{
    "_id": {
        "$oid": "5df8bd07a90a045fd1460852"
    }
}
```
I tried it with classes where properties were defined as public members and registered via `void register_class(...)`, as well as with classes where properties were defined via `Q_PROPERTY` and `QX_REGISTER_ALL_QT_PROPERTIES` makro.

**Comment by QxOrm** [comment]
If your classes inherit from [qx::IxPersistable](https://www.qxorm.com/doxygen/html/classqx_1_1_ix_persistable.html) and you are working with a pointer to a base class, then you have to use the methods prefixed by _qx_ : so for example _qxInsert_.

Documentation is here : https://www.qxorm.com/qxorm_en/manual.html#manual_450

List of available methods :
`virtual long qxCount(const qx::QxSqlQuery & query = qx::QxSqlQuery(), QSqlDatabase * pDatabase = NULL);
virtual QSqlError qxFetchById(const QVariant & id = QVariant(), const QStringList & columns = QStringList(), const QStringList & relation = QStringList(), QSqlDatabase * pDatabase = NULL);
virtual QSqlError qxFetchAll(qx::IxCollection & list, const QStringList & columns = QStringList(), const QStringList & relation = QStringList(), QSqlDatabase * pDatabase = NULL);
virtual QSqlError qxFetchByQuery(const qx::QxSqlQuery & query, qx::IxCollection & list, const QStringList & columns = QStringList(), const QStringList & relation = QStringList(), QSqlDatabase * pDatabase = NULL);
virtual QSqlError qxInsert(const QStringList & relation = QStringList(), QSqlDatabase * pDatabase = NULL);
virtual QSqlError qxUpdate(const qx::QxSqlQuery & query = qx::QxSqlQuery(), const QStringList & columns = QStringList(), const QStringList & relation = QStringList(), QSqlDatabase * pDatabase = NULL);
virtual QSqlError qxSave(const QStringList & relation = QStringList(), QSqlDatabase * pDatabase = NULL);
virtual QSqlError qxDeleteById(const QVariant & id = QVariant(), QSqlDatabase * pDatabase = NULL);
virtual QSqlError qxDeleteAll(QSqlDatabase * pDatabase = NULL);
virtual QSqlError qxDeleteByQuery(const qx::QxSqlQuery & query, QSqlDatabase * pDatabase = NULL);
virtual QSqlError qxDestroyById(const QVariant & id = QVariant(), QSqlDatabase * pDatabase = NULL);
virtual QSqlError qxDestroyAll(QSqlDatabase * pDatabase = NULL);
virtual QSqlError qxDestroyByQuery(const qx::QxSqlQuery & query, QSqlDatabase * pDatabase = NULL);
virtual qx_bool qxExist(const QVariant & id = QVariant(), QSqlDatabase * pDatabase = NULL);
virtual qx::QxInvalidValueX qxValidate(const QStringList & groups = QStringList());
virtual qx::IxPersistableCollection_ptr qxNewPersistableCollection() const;
virtual qx::IxClass * qxClass() const;`

Code example :
`QList<qx::IxPersistable *> lst = ...;
foreach(qx::IxPersistable * p, lst)
{
   QSqlError daoError = p->qxSave();
   if (daoError.isValid()) { /* an error occured */ }
   // etc...
}`

**Comment by ChrizzyM87** [comment]
Thanks! Works as expected! Great library!!!

**Comment by ChrizzyM87** [comment]
Awesome! Works as expected! Thank you!!
