### ISSUE TITLE
qxUpdate() / qxSave() Bug

### ISSUE THREAD

**Issue by ChrizzyM87** [QxOrm/QxOrm#19]
Hello,
I'm using MongoDB with a base class derived from QObject and qx::IxPersistable. Members are defined via Q_PROPERTY makros like `Q_PROPERTY(QString id READ id WRITE setId)`.
If I call qxInsert on a child object everything works fine. MongoDB shows a new entry `"_id" : ObjectId("5e13197eda4c6e7af566e143"), ...` and sets id of the object to "qx_oid:5e13197eda4c6e7af566e143" (QString type), but if I call qxUpdate() on the same object nothing is updated, because QxOrm does not find the existent database entry. If I call qxSave() on that object, QxOrm stores a new entry in MongoDB `"_id" : "qx_oid:5e13197eda4c6e7af566e143",....`
So it seems like that QxOrm is not "translating" the id correctly.

In case that members are not registered via Q_Property and are accessible directly (not only via getters/setters) everything works fine!

**Comment by ChrizzyM87** [comment]
Same problem occurs when using `qxFetchById()`. QxOrm tries to find an entry, which id is equal to a QString "qx_oid:..."

`[QxOrm] sql query (total: 1 ms, db: 1 ms) : MongoDB find one 'Person' :
{
    "_id": "qx_oid:5e13319dfacd711ce8237cd4"
}`

When not using Q_PROPERTY, everything works fine:
`[QxOrm] sql query (total: 2 ms, db: 2 ms) : MongoDB find one 'MDB_Person' :
{
    "_id": {
        "$oid": "5e1332859be2a95f82177534"
    }
}`

**Comment by QxOrm** [comment]
Hello,
Could you please try with latest source code ?
I think I have fixed your issue.
I also added a testQtProperty unit test in qxBlogMongoDB sample project.

**Comment by ChrizzyM87** [comment]
Amazing! Works as expected! Thank you a lot!!!
