### ISSUE TITLE
Silence QxOrm

### ISSUE THREAD

**Issue by ChrizzyM87** [QxOrm/QxOrm#22]
Hello!
I want to silence QxOrm to avoid qDebug outputs like

> [QxOrm] sql query (total: 2 ms, db: 1 ms) : MongoDB find one 'Person' :
> {
>     "_id": {
>         "$oid": "5e281af9a6b7557c7675fce4"
>     }
> }

I found `IxDao_Helper::quiet()` but I could not find a way to retrieve the IxDao_Helper object to access this function.
Can you please give me a hint? Thanks!!

**Comment by QxOrm** [comment]
Hello,

There are some general settings in [qx::QxSqlDatabase](https://www.qxorm.com/doxygen/html/classqx_1_1_qx_sql_database.html) singleton class.

So you should try : 
`qx::QxSqlDatabase::getSingleton()->setTraceSqlQuery(false);`

And for MongoDB, there is also this specific option : 
`qx::dao::mongodb::QxMongoDB_Helper::setLogDatabaseReply(false);`

**Comment by ChrizzyM87** [comment]
`setTraceSqlQuery(false)` did the job! Thank you!
