### ISSUE TITLE
qxFetchByQuery() Bug

### ISSUE THREAD

**Issue by ChrizzyM87** [QxOrm/QxOrm#23]
Hello :)
`qx::IxPersistable::qxFetchByQuery()` seems not to work with classes which are derived from `IxPersistable` and define attributes via Q_PROPERTY mechanism. It always returns the whole collection and does not filter by the query.

You can test this by appending the following lines to `testQtProperty()`of the qxBlogMongoDB project:

```
TestQtProperty tst2;
tst2.setDesc("tst2");
daoError = qx::dao::insert(tst2);
qAssert(!daoError.isValid());

qx::QxSqlQuery query;
query.where("desc").isEqualTo("tst update");
auto queryFetchLst = qx::IxPersistable::qxFetchByQuery("TestQtProperty", query);
qDebug() << queryFetchLst->__count();
qAssert(queryFetchLst->__count() == 1);
```
The code adds a second entry with desc == "tst2" and tries to fetch the entry which was updated before with desc == "tst update".
Best regards
Christoph

**Comment by QxOrm** [comment]
Hello,

When you write : 
`query.where("desc").isEqualTo("tst update");`
QxOrm library will create SQL code ==> so this is normal that it doesn't work with a MongoDB database.

To create filters for MongoDB, you can still use qx_query class, but you have to provide a JSON query.
This is explained in the QxOrm manual here : [JSON queries](https://www.qxorm.com/qxorm_en/manual.html#manual_992).

Example : 
`// Fetch many authors by query (only female)
list_author list_of_female_author;
qx_query query { { "sex", author::female } };
daoError = qx::dao::fetch_by_query(query, list_of_female_author);`

**Comment by ChrizzyM87** [comment]
Yes! It's working! Sorry, I thought i read somewhere that qx_query class creates JSON queries if MongoDB is selected.
