### ISSUE TITLE
Serialization Issue

### ISSUE THREAD

**Issue by jbspears** [QxOrm/QxOrm#24]
Not sure if I'm using the QxOrm serialization correctly or not, but I'm seeing an issue when serializing/deserializing a class that has one member that is also a registered class.  When I add just any member before the single member, it works fine.  I have attached an example (using MSVC2017 and Qt 5.9.8 64-bit).  Note if you uncomment the first block (serialization of another object) in main.cpp the deserialization output for the second object contains values from the first object which would seem to indicate a memory issue.  Thanks!

UPDATED:  Seems like classes without a defined ID (I'm not using database so ID isn't needed in my case) and with just one member, are not handled correctly with the serialization helper.  The following mod to QxSerializeQDataStream_qx_registered_class.cpp seems to work for me (I tested with and without an ID):

   if (qx::serialization::helper::QxSerializeCheckInstance::contains(pOwner))
   {
      qx::IxDataMember * pId = pClass->getId(true); 
      if (pId) 
      {
         bJustId = true; stream << bJustId;
         QVariant val = pId->toVariant(pOwner); stream << val;
         return stream;
      }
   }

This may not be the correct fix.  But it is something with the checker and the nesting contains test without an ID defined and one member.

[example.zip](https://github.com/QxOrm/QxOrm/files/4113166/example.zip)

**Comment by QxOrm** [comment]
Hello,
Thx for reporting this issue, and thx for your example project to reproduce it.
There is the same problem with JSON serialization (qx::cvt::to_json / qx::cvt::from_json).
I will try to fix ASAP...

**Comment by QxOrm** [comment]
Could you try to download latest source code ?
I think I have fixed your issue.

**Comment by jbspears** [comment]
Tried it with my sample project and added JSON also and it works great.  Thanks for the quick fix!!  Awesome library!

**Comment by QxOrm** [comment]
Great !
