### ISSUE TITLE
Building Mongo DB queries with OR conditions

### ISSUE THREAD

**Issue by ChrizzyM87** [QxOrm/QxOrm#26]
Hello,
I am using `qx::IxPersistable::qxFetchByQuery()` to fetch multiple elements of one class from DB.

To fetch all elements e.G. with attribute yaw == 90, I build a query by calling
```
qx::QxSqlQuery query{{"yaw", 90}};
```

To fetch all elements e.G. with attribute yaw == 90 OR yaw == -45 the solution I found was to build a query and use the aggregation framework:

```
qx::QxSqlQuery queryAggr("aggregate",
"[{ \"$match\" : { \"yaw\" : { \"$in\": [90, -45] } } }]");
```
Is this the only way to do it, or is there another (easier) way?
Best regards,
Christoph

**Comment by QxOrm** [comment]
Hello,

This is more a MongoDB question than a QxOrm library question.
Actually, it seems that $or operator exists for MongoDB : 
- https://stackoverflow.com/questions/2008032/mongodb-query-with-an-or-condition
- https://docs.mongodb.com/manual/reference/operator/query/or/#op._S_or

**Comment by ChrizzyM87** [comment]
Hello,
Yes, but I thought that there might be a function or class of QxOrm which helps with building Json queries. But no problem, I started to create one. Maybe I can provide it later.

**Comment by QxOrm** [comment]
No : for now, you have to build your JSON query yourself.
There is no tool like SQL query builder.

**Comment by ChrizzyM87** [comment]
Ok, thanks for your answer!
