### ISSUE TITLE
Progress info

### ISSUE THREAD

**Issue by ChrizzyM87** [QxOrm/QxOrm#27]
Hello,

is it somehow possible to get a progress info from QxOrm e.G. while `qx::IxPersistable::qxFetchByQuery()` or `qx::IxPersistable::qxFetchAll` is executed? A signal would be super nice, e.G. with a signature like this `void sig_progressInfo(int processed, int total);`.

Best regards,
Christoph

PS: My database module based on QxOrm is getting productive and I'm very happy using QxOrm. Thank you!!

**Comment by QxOrm** [comment]
Hello,

You should try to implement a trigger to have this kind of callback/signal : [QxOrm trigger's documentation is here](https://www.qxorm.com/qxorm_en/manual.html#manual_410).
And you can check with QxEntityEditor application to know how to write a QxOrm trigger.

I think the trigger **qx::dao::on_after_fetch** could help you to implement a progress info.

> PS: My database module based on QxOrm is getting productive and I'm very happy using QxOrm. Thank you!!

Great !

**Comment by ChrizzyM87** [comment]
Awesome! This is working! Another short question: I disabled debug output by setting setLogDatabaseReply() and setTraceSqlQuery() to false, but I still get output when I connect, including the password and username for mongo DB. How can I disable this?

> [QxOrm] Connect to MongoDB database : mongodb://rpmadmin:XXXXXXX@XXX.XXX.XXX.XXX:27777
> [QxOrm] Ping to MongoDB database server : OK
> [QxOrm] Fetch build info from MongoDB database server : 
> ...

**Comment by QxOrm** [comment]
> Awesome! This is working!

Great !

About these 3 logs, yes there is no option for now to disable them.
I will add an option soon to enable/disable them...

**Comment by ChrizzyM87** [comment]
Ok, Yes that would be an important feature!
I already have an installed MessageHandler, I can filter those logs out as a workaround! THX!

**Comment by QxOrm** [comment]
I added a new setting : 
`qx::dao::mongodb::QxMongoDB_Helper::setLogDatabaseInfo(false);`

Could you please download latest version to test it ?

**Comment by ChrizzyM87** [comment]
Works as expected! Great!!
