### ISSUE TITLE
qxFetchByQuery / qxFetchAll performance issue

### ISSUE THREAD

**Issue by ChrizzyM87** [QxOrm/QxOrm#28]
Hello,

I'm using the `qxFetchByQuery()` or `qxFetchAll()` function of `IxPersistable` class to fetch e.G. 3000 objects from MongoDB which takes like 16seconds in total. I implemented `QxDao_Trigger` for my base class to call a function every time an object is fetched (`onAfterFetch()`). 
Now I observed that it takes like 5seconds until `onAfterFetch()` is called for the first time.
QxOrm outputs the following:

>  [QxOrm] sql query (total: 16820 ms, db: 5176 ms)

Further I observed that network transfer is only active for the first 5seconds.

So I made the conclusion, that QxOrm fetches the data from MongoDB in the first 5seconds, without calling a callback fct and it continues with post processing including parsing the fetched data, creating the objects and calling `onAfterFetch()` for every one. Is that correct?

Would it be possible to change that behaviour, so that every object which is fetched from the DB is created instantly and then the next object is fetched? This would have the advantage that you can work with an object in another thread, while the rest is still beeing fetched, and that the onAfterFetch() function is called constantly to show e.G. a progress bar to the user.

I would check by myself but unfortunately it's hard for me to look through the QxOrm code and find the right place for stuff like this.

Best regards
Christoph

**Comment by QxOrm** [comment]
Hello,

Did you get these measures in **debug mode** or in **release mode** ?
There is a huge difference between debug mode and release mode, and 16s to fetch 3000 items seems too much.

> So I made the conclusion, that QxOrm fetches the data from MongoDB in the first 5seconds, without calling a callback fct and it continues with post processing including parsing the fetched data, creating the objects and calling onAfterFetch() for every one. Is that correct?

Yes, this is correct.

> Would it be possible to change that behaviour, so that every object which is fetched from the DB is created instantly and then the next object is fetched?

For now, no, this is too complex to change this behavior.
This is the behavior only for MongoDB database, for all other databases, this is a bit different.

But I think you can easily reduce the first 5 seconds : instead of loading your 3000 items in one time, you should load them per packets of 100 items for example (and loop until you have all your 3000 items fetched) ==> this way, you could have a "better" progress bar.

**Comment by ChrizzyM87** [comment]
Hello,
measures are almost the same in debug and release mode. It takes so long, because the items I fetch contain images.
To load them per packets seems to be a good idea, guess I can do this by using extra queries!? No idea how, but I will find out! Thanks!

**Comment by QxOrm** [comment]
To load them per packets with MongoDB database, just use skip() and limit() : https://docs.mongodb.com/manual/reference/method/cursor.skip/

**Comment by ChrizzyM87** [comment]
Thanks for the tip!!

**Comment by QxOrm** [comment]
I found a way to fetch items from MongoDB database without putting data in a buffer (so better performance and less memory usage).

Could you please download latest version to test it ?

You could try to load all your 3000 items without using skip()/limit() and your progress bar should be smoother.

**Comment by ChrizzyM87** [comment]
AWESOME!!!! Well done! Thanks!
