### ISSUE TITLE
MongoDB aggregration and qxDeleteByQuery()

### ISSUE THREAD

**Issue by ChrizzyM87** [QxOrm/QxOrm#29]
Hello,

I'm using the aggregation framework to fetch items from MongoDB by query using `qxFetchByQuery().` Query string is e.G.
> [{ "$match" : { "personId" : { "$in": ["qx_oid:5e4410582bb9514d6454ab36"] } } }]

This works fine.

But when I call `qxDeleteByQuery()` I get following error messages:
> Database error number '-1' : [QxOrm] Unable to delete many 'bson_t' documents
> (PersonDesc) in MongoDB database : unknown operator: $match
> MongoDB delete many 'PersonDesc' :
> [{ "$match" : { "personId" : { "$in": ["qx_oid:5e4410582bb9514d6454ab36"] } } }]

Does the `qxDeleteByQuery()` function not support the aggregation framework or am I doing something wrong? `QxSqlQuery()` is constructed with type == "aggregate" and query string like above in both cases.

Best regards
Christoph

**Comment by QxOrm** [comment]
Hello,

I read quickly the code and I think you are right : "simple" queries are supported by **qx::dao::delete** functions, but not aggregation queries.

As a workaround, you can do something like that : 
1- use **qx::dao::fetch_by_query** with your aggregation query to get all items you want to delete
2- call **qx::dao::delete_by_id** (you just need to call it once because it supports any list of items as input parameter)

Example : 
```
// 1- use qx::dao::fetch_by_query with your aggregation query to get all items you want to delete
list_author list_of_female_author_other;
qx_query queryAggregate("aggregate", "[ { \"$match\" : { \"sex\" : " + QString::number(static_cast<int>(author::female)) + " } } ]");
qx::dao::fetch_by_query(queryAggregate, list_of_female_author_other); qAssert(! daoError.isValid());

// 2- call qx::dao::delete_by_id
qx::dao::delete_by_id(list_of_female_author_other);
```

In _qxBlogMongoDB_ sample project, you have several ways to delete items from database : 
```
   // Test delete one author by id
   pAuthor.reset(new author());
   pAuthor->m_id = "my_custom_id_author_4";
   daoError = qx::dao::delete_by_id(pAuthor); qAssert(! daoError.isValid());
   qAssert(qx::dao::count<author>() == 4);
```

```
   // Test delete many author by id
   authorX.clear();
   { author author_tmp; author_tmp.m_id = author_3_id; authorX.append(author_tmp); }
   { author author_tmp; author_tmp.m_id = author_5_id; authorX.append(author_tmp); }
   daoError = qx::dao::delete_by_id(authorX); qAssert(! daoError.isValid());
   qAssert(qx::dao::count<author>() == 2);
```

```
   // Test delete author by query (all male)
#ifdef Q_COMPILER_INITIALIZER_LISTS
   int iMale = static_cast<int>(author::male);
   query = qx_query{ { "sex", iMale } };
#else // Q_COMPILER_INITIALIZER_LISTS
   query = qx_query("{ \"sex\" : " + QString::number(static_cast<int>(author::male)) + " }");
#endif // Q_COMPILER_INITIALIZER_LISTS
   daoError = qx::dao::delete_by_query<author>(query); qAssert(! daoError.isValid());
   qAssert(qx::dao::count<author>() == 1);
```

**Comment by QxOrm** [comment]
Hello,

Now *qx::dao::delete_by_query* supports MongoDB aggregation framework.
Could you try to download latest version and test it please ?

Here is my unit test :
```
   // Test delete by query using MongoDB aggregation framework (delete all female)
   qx_query queryAggregate("aggregate", "[ { \"$match\" : { \"sex\" : " + QString::number(static_cast<int>(author::female)) + " } } ]");
   daoError = qx::dao::delete_by_query<author>(queryAggregate); qAssert(! daoError.isValid());
   qAssert(qx::dao::count<author>() == 2);
```

**Comment by ChrizzyM87** [comment]
Hello,
i merged your changes, but now my application crashes at startup, when     `qx::QxClassX::registerAllClasses(true);` is called.
![grafik](https://user-images.githubusercontent.com/21241672/76234394-f7df2900-6229-11ea-9b7d-a94720fa7bf7.png)

**Comment by QxOrm** [comment]
Arf this is possible because I changed a lot qx::QxCollection class.
But all my unit tests are ok, so I don't understand.
Are you sure you clean and rebluid everything ?
Could you please try to execute qxBlogMongoDB sample project ?

**Comment by ChrizzyM87** [comment]
I did a complete rebuild of my application, now everything is working :) Thanks!

**Comment by QxOrm** [comment]
Great !
