### ISSUE TITLE
[MongoDB] Support DBRefs type for foreign key of relations.

### ISSUE THREAD

**Issue by Andreychikov-Vasiliy** [QxOrm/QxOrm#31]
https://docs.mongodb.com/manual/reference/database-references/#dbrefs

As I understand this is useful when you have for example one-to-many (1-n) relation, and "n" isn't ref to single collection (because of Concrete Table Inheritance strategy )

**Comment by QxOrm** [comment]
Hello,

Sorry I don't understand : QxOrm library already supports relationships with MongoDB database, this is explained in the QxOrm manual here : https://www.qxorm.com/qxorm_en/manual.html#manual_993

Could you please provide an example where dbrefs could be useful, and something not already supported by QxOrm library ?

**Comment by Andreychikov-Vasiliy** [comment]
Ok, will try demonstrate it with code as soon as possible.

**Comment by Andreychikov-Vasiliy** [comment]
Here my fork with branch with two demo commits https://github.com/Andreychikov-Vasiliy/QxOrm/commits/for_demo
I will write additional reply here with detailed description for each commit later.

**Comment by Andreychikov-Vasiliy** [comment]
Sorry for long delay. So, it is not real world example. It is just abstract continuation of QxBlog demo project.  I've commited two state that I added to describe pre-issue case in first commit. And second it's the problem itself.
So *[first](https://github.com/Andreychikov-Vasiliy/QxOrm/commit/347b97fcd891a31c66aeec7363cf9812d462f520)* - it is just extending our models with two new ones. All they related to *blog* entity as 1 (blog) - to many <our_entity> 
Short description of purpose of that's models:
1. BlogQuote - text comment to some part of blog contents (and therefore have two fields which refers to begin and end of text position related to quote)
2.  Donation - it is just money support to author from community.
Also, i I've added same field to that entities and to already existing *comment* entity - user_id (just for example).

And now *[second](https://github.com/Andreychikov-Vasiliy/QxOrm/commit/6ba17587f9cc4b3c1b31518e9077dee143149c12)* commit:
We can notice that all this entities related to blog (comment, blog_quote, donation) have some share base (user and date). So tried generalize that entities to inherit that properties from parent entity(class) and called it *reaction*. 

I've tried to do this according to manual with no luck (compilation give error messages, that I can't understand). 

Also, I found that MongoDB have and recommend some approach to store such inheritance relations in DB https://docs.mongodb.com/manual/reference/database-references/#dbrefs (Where *blog_quote*, *donation*, and *comment* will be stored in separate collections, but reference to them from blog - is just same property in *blog* entity)

**Comment by QxOrm** [comment]
Hello,

Ok I think I understand what you try to do : you want to define a base class where you put some common properties + some relationships. Then you want to inherit from this base class to define your real model/classes.

With QxOrm library, you can create a base class (which could be abstract) and define "simple" properties (by "simple", I mean : no relationship). And then, all classes which inherit from this base class will have automatically all "simple" properties registered in QxOrm context in the base class.

**BUT you can't define relationships in a base class with QxOrm library**.
You must define your relationships in your concrete classes.
This is explained in the manual here : [QxOrm library supports only Concrete Table Inheritance strategy](https://www.qxorm.com/qxorm_en/manual.html#manual_440).

So in your example, you have to define the n-1 _blog_id_ relationship in : _donation_, _comment_ and _blog_quote_ classes.
But you can keep in your _reaction_ base class "simple" properties like : _m_id_, _m_dt_create_, _m_user_id_.

There is an example in the QxOrm manual of base class [here](https://www.qxorm.com/qxorm_en/manual.html#manual_450) :
- [QxPersistable.hpp file](https://www.qxorm.com/qxorm_en/resource/qx_persistable_hpp.html) ;
- [QxPersistable.cpp file](https://www.qxorm.com/qxorm_en/resource/qx_persistable_cpp.html).
 FYI, we use this class (_QxPersistable_) in QxEntityEditor application which is based on QxOrm library.

As you understand, this is exactly the same thing for QxOrm library with other SGBD like Oracle, MariaDB, SQLite or whatever : this is not specific to MongoDB database.

**Comment by Andreychikov-Vasiliy** [comment]
Nice to hear that. I will try to fix base class in my code to and check how it will work with MongoDB.
