### ISSUE TITLE
How send a qx_table_class to Qml ?

### ISSUE THREAD

**Issue by mv2050arshad** [QxOrm/QxOrm#37]
Hi. at first i would like to appreciated you for your great ORM.

I created my database model using your Gui software and i used my table and CRUD operation in c++ easy, 
but i dont know how to send those class table directly to QML!? because i define some more method in that class for each tableClass and i want to call it directly in QML. 
how i do that?

**Comment by QxOrm** [comment]
Hello,

For QML, I would recommend to test [the QxRestApi module](https://www.qxorm.com/qxorm_en/manual.html#manual_97).
A sample project is available in _./test/_ directory of QxOrm package.

Another option is to use [the QxModelView module](https://www.qxorm.com/qxorm_en/manual.html#manual_90).
You have also a sample project in _./test/_ directory of QxOrm package.

But I think that **QxRestApi module** is easier to use than model/view.

**Comment by mv2050arshad** [comment]
thank you
