### ISSUE TITLE
Add explicit commit function to QxSession

### ISSUE THREAD

**Issue by MasterMind2k** [QxOrm/QxOrm#43]
Hi.

I would like to see an explicit commit feature in QxSession. It would make it's use a little bit more safer, since there may be multiple scenarios where you need to rollback a transaction and exactly one scenario that should commit the transaction.

Granted, if there is an error with the query, it will rollback by itself. But if we have some logical error (empty table, etc.), we need to be careful not to forget to rollback the transaction.

As a work-around I've made a simple wrapper class around QxSession that requires an explicit commit, otherwise will rollback on its destruction.

**Comment by QxOrm** [comment]
Hello,
Could you please provide your wrapper class ?

**Comment by MasterMind2k** [comment]
Will do. Hopefully by the monday!

**Comment by MasterMind2k** [comment]
Here it is, the class:
```cpp
class ScopedSession {
public:
  explicit ScopedSession(qx::QxSession *session)
      : m_session(session), m_isComitted(false) {}
  ~ScopedSession() {
    if (!m_isComitted)
      m_session->rollback();
  }

  void commit() {
    if (!m_session->isValid())
      return;

    m_session->commit();
    m_isComitted = true;
  }

private:
  qx::QxSession *m_session;
  bool m_isComitted;
};
```

And an attempts at writing test cases:
```cpp
void TestScopedSession::test_commit() {
  // TODO To verify this test, read it's output
  useMemoryStorage();
  useInitLevel();

  qx::QxSession session;
  {
    ScopedSession scoped(&session);

    scoped.commit();
  }
}

void TestScopedSession::test_rollback() {
  // TODO To verify this test, read it's output
  useMemoryStorage();
  useInitLevel();

  qx::QxSession session;
  { ScopedSession scoped(&session); }
}
```

**Comment by QxOrm** [comment]
Hello,

If I add a property like this : **qx::QxSession::setAutoRollbackWhenDestroyed();**
And if I add this line in the **close()** method called by the QxSession destructor : 

```
bool QxSession::close()
{
   bool bCloseOk = true;
   if (m_pImpl->m_bTransaction && m_pImpl->m_bAutoRollbackWhenDestroyed) { bCloseOk = rollback(); }
   else if (m_pImpl->m_bTransaction && isValid()) { bCloseOk = commit(); }
   else if (m_pImpl->m_bTransaction) { bCloseOk = rollback(); }
   if (m_pImpl->m_bAutoOpenClose) { m_pImpl->m_database.close(); m_pImpl->m_bAutoOpenClose = false; }
   return bCloseOk;
}
```

Is it ok for you and sufficient to not use your wrapper class ?

**Comment by MasterMind2k** [comment]
It looks good, yes. It will have an additional line, but it is better than changing the default behavior.

What about (it may be ugly, not sure) static "constructor" methods like:
```cpp
{
  auto session = qx::QxSession::withExplicitCommit();
  ...
}
```

Just an idea. You suggestion will also work.
```cpp
{
  qx::QxSession session;
  session.setAutoRollbackWhenDestroyed(true);
  ...
}
```

**Comment by QxOrm** [comment]
Done in the latest commit.
