### ISSUE TITLE
How to make UNION queries?

### ISSUE THREAD

**Issue by MasterMind2k** [QxOrm/QxOrm#44]
Hi.

Can UNION queries be done in this ORM?

An example:
```
select
  col1
  ,col2
from (
  select col1, col2, col3 from table1
  union select col1, col2, col3 from table1
)
where
  col3 = value
```

**Comment by QxOrm** [comment]
Hello,
With [qx_query class](https://www.qxorm.com/doxygen/html/classqx_1_1_qx_sql_query.html) : no.
But you could use : 
- [qx::dao::execute_query<T>()](https://www.qxorm.com/qxorm_en/manual.html#manual_3610) and create a (read only ?) persistent C++ class to store the SQL result.
- or use [qx::dao::call_query()](https://www.qxorm.com/qxorm_en/manual.html#manual_3610) and iterate manually over the SQL result.
- or use Qt SQL functions.

**Comment by MasterMind2k** [comment]
Ha, I've missed the `execute_query`. I used the `call_query`. Thank you.

Would it be possible for repository to be able to do union by itself? The use case is, that  I have an abstract model that is sub-classed by 3 models. And I would like to implement searching on common properties through all three models.

Now, how repository work is, that abstract model has no table named, so he auto-generates it and believes that there is some non-existant table.

**Comment by QxOrm** [comment]
Hello,
I don't understand : _abstract model has no table named, so he auto-generates it and believes that there is some non-existant table._
Could you please provide an example ?

**Comment by MasterMind2k** [comment]
Let us say we have three classes.
```cpp
class A {
  // Abstract
};

class B : public A {
  // with some attributes
  // map this class to table_b
};

class C : public A {
  // with some attributes
  // map this class to table_c
};
```

ORM will create three tables:
  * table_b
  * table_c

When you try to fetch data with abstract class, it will create the following SQL:
```sql
select * from A;
```

But it could do something like:
```sql
  select
    -- fields declared in class A
  from (
    select * from table_b
    union
    select * from table_c
  )
```

I do agree that this would create suboptimal queries and a better way would be to implement this inheritance using one-to-one relationships. But QxOrm does not support it.

**Comment by QxOrm** [comment]
Hello,
No QxOrm library will no support it natively.
You must create your own SQL query yourself using Qt SQL or _qx::dao::execute_query()_ or _qx::dao::call_query()_.

Another option could be to customize the SQL query generated by QxOrm library using this callback (**onBeforeSqlPrepare**) : 
1- create your own SQL generator sub-classing one of the generator provided by QxOrm library ([example here](https://www.qxorm.com/qxorm_en/manual.html#manual_310)) : 
```
   qx::dao::detail::IxSqlGenerator_ptr pSqlGenerator;
   pSqlGenerator.reset(new qx::dao::detail::QxSqlGenerator_MSSQLServer());   
   qx::QxSqlDatabase::getSingleton()->setSqlGenerator(pSqlGenerator);
```
2- in your SQL generator class, override the method : 
` virtual void onBeforeSqlPrepare(IxDao_Helper * pDaoHelper, QString & sql) const;`

This way, if **pDaoHelper->getDataMemberX()->getClass()** is your abstract class then you can change the SQL as you want.

**Comment by MasterMind2k** [comment]
Nice. Thank you.
