### ISSUE TITLE
QTime Qt5 Default Constructor

### ISSUE THREAD

**Issue by Kasuax** [QxOrm/QxOrm#46]
We noticed that the Qt5.9.7 QTime default constructor does not provide the same object that it used to in Qt4.  

QTime() is invalid
QTime(0,0) is 0

Do you think this will impact the implementation of this class when compiled with Qt5?

https://github.com/QxOrm/QxOrm/blob/4d370e5c09118670bd915c20063074551da37bd3/include/QxDao/QxTimeNeutral.h#L98

**Comment by QxOrm** [comment]
Hello,

No I think there is no impact between Qt4/Qt5/Qt6, because in the _qx::QxTimeNeutral::update()_ method, there is this condition : 
`if (m_time.isValid())`

which is the same result for a default constructed QTime instance (_false_).

**Comment by Kasuax** [comment]
Thank you very much for investigating this for us.
