### ISSUE TITLE
Refactor find_package(Qt5…) calls

### ISSUE THREAD

**Issue by elfring** [QxOrm/QxOrm#5]
The command “`find_package`” is used a few times for build checks around Qt software components in [CMake scripts](https://github.com/QxOrm/QxOrm/blob/2575415c1d464e060fba2b3796255bd7565d9b89/QxOrm.cmake#L102 "Checking Qt build dependencies").
I suggest to combine these commands in [the way which was described by Marcus D. Hanwell on 2016-10-21](https://blog.kitware.com/cmake-finding-qt5-the-right-way/ "CMake: Finding Qt 5 the “Right Way”").

**Comment by QxOrm** [comment]
Thx for the code review !

**Comment by QxOrm** [comment]
Should be ok (at least better) with the latest commit to support Qt6.
