### ISSUE TITLE
Qt6 compilation problem already defined error in obj files

### ISSUE THREAD

**Issue by omortie** [QxOrm/QxOrm#62]
Hello,
I've been using QxOrm for a while and I had no problem with msvc 2022(v143) and Qt 5.15.2 until now 
but I tried to switch my application to Qt6 and I've updated QxOrm library to version 1.4.9 which supports Qt 6 packages.
I have no problem in build time but in link time I will get errors like this one:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2005	"private: long __cdecl qx::QxDataMemberX<class qx::trait::no_base_class_defined>::count_WithDaoStrategy_Helper(void)const " (?count_WithDaoStrategy_Helper@?$QxDataMemberX@Vno_base_class_defined@trait@qx@@@qx@@AEBAJXZ) already defined in mocs_compilation.cpp.obj	D:\Programming\Work\Qt6\QxOrm\out\build\x64-Debug\QxOrm	D:\Programming\Work\Qt6\QxOrm\out\build\x64-Debug\QxSingletonInit.cpp.obj	1	
```

despite I have no problem in compiling and using this version with Qt 5.15.2 and the same toolchain

**Comment by QxOrm** [comment]
Hello,

By "version 1.4.9" : do you mean you download latest version from GitHub (it should be : QxOrm_1.4.9_BETA_18) ?

About MSVC 2022, I didn't test it yet (I don't have any issue with MSVC 2019 and Qt6).
It seems that you have a conflict with the moc generated files.

I don't know if this is related, but when a QxOrm registered class inherits from QObject, QxEntityEditor adds something like this in the header file : 

```
#ifdef _QX_NO_PRECOMPILED_HEADER
#ifndef Q_MOC_RUN
#include "../include/qxBlog_precompiled_header.gen.h" // Need to include precompiled header for the generated moc file
#endif // Q_MOC_RUN
#endif // _QX_NO_PRECOMPILED_HEADER
```

**Comment by omortie** [comment]
actually yes my repository is updated to the latest version on Github
my problem still exists using even MSVC2019 with Qt6 but if I change my Toolchain to Qt5.15.2 and (msvc 2019 or 2022) it will compile and link successfully.
the problem is with Qt6.2.2 not the compiler

**Comment by QxOrm** [comment]
What I have done : 
- install latest version of Qt (Qt 6.2.3 for MSVC 2019 64 bits)
- change my QT6_0_MSVC2019_64B environment variable to be able to run the script below
- run msvc2019_build_all_debug_64b_minimal.bat from ./QxOrm/tools/ directory

Everything is fine : no compile error, no link error, and everything is running without any error.

Please note that the msvc2019_build_all_debug_64b_minimal.bat script uses cmake to build QxOrm library and all samples projects. But it uses MSVC 2019 compiler/linker.

**Comment by mattcwill** [comment]
> What I have done :
> 
> * install latest version of Qt (Qt 6.2.3 for MSVC 2019 64 bits)
> * change my QT6_0_MSVC2019_64B environment variable to be able to run the script below
> * run msvc2019_build_all_debug_64b_minimal.bat from ./QxOrm/tools/ directory
> 
> Everything is fine : no compile error, no link error, and everything is running without any error.
> 
> Please note that the msvc2019_build_all_debug_64b_minimal.bat script uses cmake to build QxOrm library and all samples projects. But it uses MSVC 2019 compiler/linker.

Just wanted to chime in and say I am getting the exact same errors, including when following the steps above exactly as far as I can tell. Would you mind sharing what version of CMake you are using? I am using 3.23.2. I also am successful using Qt 5.

**Comment by QxOrm** [comment]
Hello,
My version of cmake is : _cmake version 3.19.3_
But it should work with latest versions.

**Comment by ianshade** [comment]
I stumbled upon the same issue with Qt 6.2.3 and MSVC 2019. It turns out that my compiler needs `QX_GCC_WORKAROUND_TEMPLATE_SPEC_INLINE` to be defined as `inline` to stop these errors.

**Comment by QxOrm** [comment]
Thx for the tip :)

**Comment by nickcole** [comment]
I was troubled for a long time, until I saw your post！

**Comment by ChaoII** [comment]
> I stumbled upon the same issue with Qt 6.2.3 and MSVC 2019. It turns out that my compiler needs to be defined as to stop these errors.`QX_GCC_WORKAROUND_TEMPLATE_SPEC_INLINE``inline`

where should I add this macro ?  msvc 2019 and qt 6.2.4

**Comment by ChaoII** [comment]
> where should I add this macro ? msvc 2019 and qt 6.2.4

where should I add this macro ? msvc 2019 and qt 6.2.4

**Comment by ChaoII** [comment]
> Thanks！ I also encountered the same problem. According to your experience, I solved it！

where should I add this macro ? msvc 2019 and qt 6.2.4

**Comment by omortie** [comment]
thank you
