### ISSUE TITLE
REST API SUPPORT FOR MONGO DB

### ISSUE THREAD

**Issue by awesomeerictech** [QxOrm/QxOrm#70]
Hello seems like mongodb isn't supported by REST API module , it would be of great help if that functionality was added to QxORM.

**Comment by QxOrm** [comment]
Hello,
Why do you say that ?
The QxOrm REST API should support MongoDB database.

https://www.qxorm.com/qxorm_en/manual.html#manual_97

**Comment by awesomeerictech** [comment]
It is working with other databases but for MongoDB it claims that the driver is not found, the driver is not the problem here because mongo blog test example is running fine , the problem is that you have restricted the API to load drivers known by qt that is sqlite,oracle,mysql and postgresql .

**Comment by awesomeerictech** [comment]
QJsonValue QxRestApi::processRequest(const QJsonValue & request)
{
   m_pImpl->clear();
   m_pImpl->m_db = qx::QxSqlDatabase::getDatabase(m_pImpl->m_error);
   if (m_pImpl->m_error.isValid()) { m_pImpl->buildError(m_pImpl->m_error); return m_pImpl->m_errorJson; }
   if (request.isArray()) { return m_pImpl->processRequestAsArray(request); }
   m_pImpl->m_requestJson = request;
   if (! m_pImpl->doRequest()) { return m_pImpl->m_errorJson; }
   return m_pImpl->m_responseJson;
}

**Comment by awesomeerictech** [comment]
qx::dao::detail::IxSqlGenerator * QxSqlDatabase::getSqlGenerator()
{
   if (m_pImpl->m_lstGeneratorByDatabase.count() > 0)
   {
      Qt::HANDLE lCurrThreadId = QThread::currentThreadId();
      QString sDatabaseKey = (m_pImpl->m_lstCurrDatabaseKeyByThread.contains(lCurrThreadId) ? m_pImpl->m_lstCurrDatabaseKeyByThread.value(lCurrThreadId) : QString());
      if (m_pImpl->m_lstGeneratorByDatabase.contains(sDatabaseKey)) { return m_pImpl->m_lstGeneratorByDatabase.value(sDatabaseKey).get(); }
   }
   if (m_pImpl->m_lstGeneratorByThread.count() > 0)
   {
      Qt::HANDLE lCurrThreadId = QThread::currentThreadId();
      if (m_pImpl->m_lstGeneratorByThread.contains(lCurrThreadId)) { return m_pImpl->m_lstGeneratorByThread.value(lCurrThreadId).get(); }
   }

   if (m_pImpl->m_pSqlGenerator) { return m_pImpl->m_pSqlGenerator.get(); }
   QMutexLocker locker(& m_pImpl->m_oDbMutex);

   if (m_pImpl->m_sDriverName == "QMYSQL")         { m_pImpl->m_pSqlGenerator = std::make_shared<qx::dao::detail::QxSqlGenerator_MySQL>(); }
   else if (m_pImpl->m_sDriverName == "QPSQL")     { m_pImpl->m_pSqlGenerator = std::make_shared<qx::dao::detail::QxSqlGenerator_PostgreSQL>(); }
   else if (m_pImpl->m_sDriverName == "QSQLITE")   { m_pImpl->m_pSqlGenerator = std::make_shared<qx::dao::detail::QxSqlGenerator_SQLite>(); }
   else if (m_pImpl->m_sDriverName == "QOCI")      { m_pImpl->m_pSqlGenerator = std::make_shared<qx::dao::detail::QxSqlGenerator_Oracle>(); }

   if (! m_pImpl->m_pSqlGenerator) { m_pImpl->m_pSqlGenerator = std::make_shared<qx::dao::detail::QxSqlGenerator_Standard>(); }
   m_pImpl->m_pSqlGenerator->init();
   return m_pImpl->m_pSqlGenerator.get();
}

**Comment by awesomeerictech** [comment]
There is no function that returns a mongoDB instance

**Comment by awesomeerictech** [comment]
#ifdef _QX_ENABLE_MONGODB
#include <QxDao/QxMongoDB/QxMongoDB_Helper.h>
#endif // _QX_ENABLE_MONGODB

doesn't help much with RestAPI module

**Comment by awesomeerictech** [comment]
QSqlError initDatabase(qx_db_collection & coll)
   {
      QSqlError err = initPool(); if (err.isValid()) { return err; }
      coll.client = std::make_shared<qx_scoped_wrapper<mongoc_client_t> >(m_pPool->get());
      if (! coll.client->get()) { return QSqlError("[QxOrm] Unable to get a MongoDB client connection from pool of type 'mongoc_client_t'", "", QSqlError::UnknownError); }
      std::string dbName = toStdString(qx::QxSqlDatabase::getSingleton()->getDatabaseName());
      if (dbName.empty()) { return QSqlError("[QxOrm] Unable to connect to MongoDB database : please define a database name using qx::QxSqlDatabase::getSingleton()->setDatabaseName()", "", QSqlError::UnknownError); }
      coll.db = std::make_shared<qx_scoped_wrapper<mongoc_database_t> >(coll.client->get(), dbName);
      if (! coll.db->get()) { return QSqlError("[QxOrm] Unable to create a 'mongoc_database_t' instance from MongoDB database (" + qx::QxSqlDatabase::getSingleton()->getDatabaseName() + ")", "", QSqlError::UnknownError); }
      return QSqlError();
   }

**Comment by awesomeerictech** [comment]
not working FYI !

**Comment by muchirajunior** [comment]
use python or JavaScript.

those two work perfect with mongo db

**Comment by QxOrm** [comment]
Hello,

> not working FYI !
Yes I just tested it and you are right.

Here is a small patch to make it to work fine, class **/QxOrm/src/QxRestApi/QxRestApi.cpp**, change the method **processRequest** like this : 

```
QJsonValue QxRestApi::processRequest(const QJsonValue & request)
{
   m_pImpl->clear();

   if (qx::QxSqlDatabase::getSingleton()->getDriverName() == "QXMONGODB") {
      m_pImpl->m_db = QSqlDatabase();
   }
   else {
      m_pImpl->m_db = qx::QxSqlDatabase::getDatabase(m_pImpl->m_error);
   }

   if (m_pImpl->m_error.isValid()) { m_pImpl->buildError(m_pImpl->m_error); return m_pImpl->m_errorJson; }
   if (request.isArray()) { return m_pImpl->processRequestAsArray(request); }
   m_pImpl->m_requestJson = request;
   if (! m_pImpl->doRequest()) { return m_pImpl->m_errorJson; }
   return m_pImpl->m_responseJson;
}
```

I tested it quickly and it seems ok now.
If you confirm, I will add this patch for the 1.4.9 release.

**Comment by awesomeerictech** [comment]
issue solved and need to be closed

**Comment by QxOrm** [comment]
Fix available in latest commit.
