### ISSUE TITLE
How can a registered class bind multiple tables with different table names but the same fields

### ISSUE THREAD

**Issue by xiaocai123123** [QxOrm/QxOrm#80]
struct CameraSceneTableInfo
{
	long cameraSceneTableIdx;
	QString cameraSceneName;
	double exposureTime;
	double gain;
	CameraTriggerMode triggerMode;
	QString note;
	CameraTableInfo cameraTableInfo;
};
QX_REGISTER_HPP_QX_BASEMODULE(CameraSceneTableInfo, qx::trait::no_base_class_defined, 0)

QX_REGISTER_CPP_QX_BASEMODULE(CameraSceneTableInfo)
namespace qx {
	template <> void register_class(QxClass<CameraSceneTableInfo>& t)
	{
		t.setName("Table");
		t.id(&CameraSceneTableInfo::cameraSceneTableIdx, CameraSceneTableInfo_CameraSceneTableIdx);
		t.data(&CameraSceneTableInfo::cameraSceneName, CameraSceneTableInfo_CameraSceneName);
		t.data(&CameraSceneTableInfo::exposureTime, CameraSceneTableInfo_ExposureTime);
		t.data(&CameraSceneTableInfo::gain, CameraSceneTableInfo_Gain);
		t.data(&CameraSceneTableInfo::triggerMode, CameraSceneTableInfo_TriggerMode);
		t.data(&CameraSceneTableInfo::note, CameraSceneTableInfo_Note);
	}
}

As above, I have a class that binds to a database table named “Table”. How can i bind a table called "Table2" with the same field

**Comment by QxOrm** [comment]
Hello,

If you want several tables with the same columns, you can use inheritance : 
https://www.qxorm.com/qxorm_en/manual.html#manual_440

You can find an example in  ./test/qxDllSample/dll2/ directory of QxOrm package with BaseClassTrigger and Foo classes : 
- https://github.com/QxOrm/QxOrm/blob/master/test/qxDllSample/dll2/qx/BaseClassTrigger.qx.cpp
- https://github.com/QxOrm/QxOrm/blob/master/test/qxDllSample/dll2/include/Foo.h

You can also design your classes with QxEntityEditor application to know how it generates with C++ inheritance : 
https://www.qxorm.com/qxorm_en/manual_qxee.html#entity_params

Only drawback about inheritance is that it doesn't support relationships.
You have to define your relations in each sub-classes.

**Comment by xiaocai123123** [comment]
Thanks
