### ISSUE TITLE
bug report:[Microsoft][ODBC SQL Server Driver][SQL Server]Cannot update identity column 'blog_id'.

### ISSUE THREAD

**Issue by nickcole** [QxOrm/QxOrm#84]
I find this bug When i run 'qxBlogExec' sample project.
**1. Running environment is:**
MS Windows 11 64bit 
MS SQL Server 2019
QT desktop 5.15.2 
MSVC 2019 64bit
QxOrm_1.4.9_BETA_23
QxEntityEditor 1.2.6

**2. how to reshow this bug**
2.1 In 'qxBlogExec' sample project,change sqlite db to ms sqlserver 2019 expression db
code like:
```
        qx::QxSqlDatabase::getSingleton()->setDriverName("QODBC3");
        QString dsn = QString("DRIVER={SQL Server};SERVER=%1;DATABASE=%2;Trusted_Connection=yes")
                .arg(R"(MYPC\TEW_SQLEXPRESS)","qxblog");
        qx::QxSqlDatabase::getSingleton()->setDatabaseName(dsn);
```
        
2.2 which line code throw error
```
   // Add 2 categories to 'blog_1' => must insert into extra-table 'category_blog'
   blog::type_list_of_category lst_category;
   lst_category.insert(category_1->getcategory_id(), category_1);
   lst_category.insert(category_3->getcategory_id(), category_3);
   blog_1->setlist_of_category(lst_category);
   daoError = qx::dao::save_with_relation("list_of_category", blog_1);
```
 
2.3 error text
[QxOrm] sql query (total: 4.81 ms, db_exec: 3.2 ms) : SELECT t_blog.blog_id AS t_blog_blog_id_0 FROM t_blog WHERE t_blog.blog_id = :blog_id
QODBCResult::exec: Unable to execute statement: "[Microsoft][ODBC SQL Server Driver][SQL Server]Cannot update identity column 'blog_id'. [Microsoft][ODBC SQL Server Driver][SQL Server]Statement(s) could not be prepared."
[QxOrm] execute sql query failed : UPDATE t_blog SET blog_id = :blog_id, title = :title, text = :text, author = :author WHERE blog_id = :blog_id_bis
Database error number '
8180' : 
QODBC3: Unable to execute statement

[Microsoft][ODBC SQL Server Driver][SQL Server]Cannot update identity column 'blog_id'. [Microsoft][ODBC SQL Server Driver][SQL Server]Statement(s) could not be prepared.
[QxOrm] dump sql query bound values : 
  - :author : 14
  - :blog_id : 5
  - :blog_id_bis : 5
  - :text : update blog_text_1
  - :title : blog_title_1

**3. analysis**
  sql query:UPDATE t_blog SET blog_id = :blog_id, title = :title, text = :text, author = :author WHERE blog_id = :blog_id_bis
  blog_id is identity (AUTO_INCREMENT) and should not update 

  **4. Other similar problems**
     in this code:
```
     // Update only property 'm_text' of 'blog_isdirty'
   daoError = qx::dao::update_optimized(blog_isdirty);
```
   
   The generated sql statement is：
`   UPDATE t_blog SET blog_id = :blog_id, text = :text WHERE blog_id = :blog_id_bis`
   
   I think it should be
`UPDATE t_blog SET text = :text WHERE blog_id = :blog_id_bis'`

   ' blog_id = :blog_id' after 'SET' should not show.
   
**5.suggestion**
  For 'id' column, if the value is not changed,'id=:id' should not show in 'UPDATE ... SET' statement
  The methods involved include:  
	qx::dao::update : update an instance (or a list of instances) to database ;
	qx::dao::update_with_relation : update an instance (or a list of instances) + its relationships to database ;
	qx::dao::update_with_all_relation : update an instance (or a list of instances) + all relationships to database ;
	qx::dao::update_by_query : update an instance (or a list of instances) to database with a SQL query filter ;
	qx::dao::update_by_query_with_relation : update an instance (or a list of instances) + its relationships to database with a SQL query filter ;
	qx::dao::update_by_query_with_all_relation : update an instance (or a list of instances) + all relationships to database with a SQL query filter ;
	qx::dao::update_optimized : update only modified fields of an instance (or a list of instances) to database using is dirty pattern and qx::dao::ptr class features ;
	qx::dao::update_optimized_by_query : update only modified fields of an instance (or a list of instances) to database using is dirty pattern and qx::dao::ptr class features with a SQL query filter ;

	qx::dao::save : insert (if entity doesn't exist in database) or update (if entity already exists in database) ;
	qx::dao::save_with_relation : insert (if entity doesn't exist in database) or update (if entity already exists in database) + its relationships ;
	qx::dao::save_with_all_relation : insert (if entity doesn't exist in database) or update (if entity already exists in database) + all relationships ;
	qx::dao::save_with_relation_recursive : insert (if entity doesn't exist in database) or update (if entity already exists in database) + all relationships on all levels (recursively) : useful to store quickly a complex tree structure for example ;

**Comment by QxOrm** [comment]
Hello,

> 2.1 In 'qxBlogExec' sample project,change sqlite db to ms sqlserver 2019 expression db

You should also change the SQL generator to SQL Server, something like this : 
```
   qx::dao::detail::IxSqlGenerator_ptr pSqlGenerator;
   pSqlGenerator.reset(new qx::dao::detail::QxSqlGenerator_MSSQLServer());   
   qx::QxSqlDatabase::getSingleton()->setSqlGenerator(pSqlGenerator);  
``` 

Documentation : https://www.qxorm.com/qxorm_en/manual.html#manual_310

**Comment by nickcole** [comment]
I do as your reply.
**The project work fine!**
Thanks for your reply.

**Comment by nickcole** [comment]
I still have a question：

**If 'id' value is not changed,  why does 'id=:id' appear in 'UPDATE ... SET' statement for mysql or sqlite?**

For ms sql server：
this code:
```
     // Update only property 'm_text' of 'blog_isdirty'
   daoError = qx::dao::update_optimized(blog_isdirty);
```

The generated sql statement is：
`UPDATE t_blog SET text = :text WHERE blog_id = :blog_id_bis`

why mysql or sqlite is:
`UPDATE t_blog SET blog_id = :blog_id, text = :text WHERE blog_id = :blog_id_bis`

I think **'UPDATE t_blog SET text = :text WHERE blog_id = :blog_id_bis' is better.**

**Comment by QxOrm** [comment]
Hello, to be honest I don't remember why this is done like this. But I know this is working fine like this for many people using the library, so I don't think I will change this behavior.

**Comment by nickcole** [comment]
thanks.
I understand your opinion.
I hope the QxOrm will become better and better!
