### ISSUE TITLE
QxOrm - Feature request:Optimistic concurrency control

### ISSUE THREAD

**Issue by nickcole** [QxOrm/QxOrm#85]
QxOrm - Feature request:Optimistic concurrency control
 [From Wikipedia website](https://en.wikipedia.org/wiki/Optimistic_concurrency_control)
**Optimistic concurrency control (OCC)**, also known as optimistic locking, is a concurrency control method applied to transactional systems such as relational database management systems and software transactional memory. OCC assumes that multiple transactions can frequently complete without interfering with each other. While running, transactions use data resources without acquiring locks on those resources. Before committing, each transaction verifies that no other transaction has modified the data it has read. If the check reveals conflicting modifications, the committing transaction rolls back and can be restarted.

**For references** 
 [Concurrency Management in Entity Framework Core]( https://www.learnentityframeworkcore.com/concurrency)
and  [Optimistic Concurrency Control Free .NET ORM Library (XPO)](https://docs.devexpress.com/eXpressAppFramework/113596/business-model-design-orm/business-model-design-with-xpo/optimistic-concurrency-control)

**I suggest  each class add a 'ObjectVersion' property***

for example:
```
class drug
{
public:
   long id;
   QString name;
   QString description;
   
   int objectVersion;
      
   drug() : id(0) { ; }
   virtual ~drug() { ; }
};
```

when update,Generate sql statement like this:

```
update drug set name=:name,description=:description,
objectVersion=:objectVersion+1 
where id=:id_bis and objectVersion=:objectVersion
```

User A might retrieve a object, followed by User B. The objectVersion value for the object will be the same for both users. 
If User B submits changes, the objectVersion value in the table will increment by 1 for that object. 
If User A subsequently tries to modify the same object, the objectVersion value in their WHERE clause combined with the primary key value will no longer match an existing row in the database and QxOrm will throw a UpdateConcurrencyException.

 **Are you interested in adding such functions?**

**Comment by QxOrm** [comment]
Hello,
I think this kind of checks should be managed by the database natively.

**Comment by nickcole** [comment]
ok.
I understand it
