### ISSUE TITLE
QxOrm - Feature request: using c++17 std::optional to manage NULL value

### ISSUE THREAD

**Issue by nickcole** [QxOrm/QxOrm#86]
**Currently** 
QxOrm library provides three ways to manage NULL value :
    1.using boost::optional class provided by boost library ;
    2.using QVariant class provided by Qt framework ;
    3.using pointers or smart-pointers : a C++ NULL pointer is associated to a NULL value in database.

**In the three ways**
boost::optional<T> class provided by boost is the best solution to manage NULL value in C++.

**c++17 std:::optional also provides this capability**

**If this feature is added, QxOrm can not rely on boost library and is another best  way to manage NULL value in C++.**

**Comment by QxOrm** [comment]
Hello,

**std::optional** is already supported since QxOrm 1.4.4, here is the line of the changes log : 

> - Support std::optional<T> (if your compiler supports C++17 features) to manage NULL database value : new header available named <QxExtras/QxStdOptional.h> to include just after <QxOrm.h> header file (ideally in a precompiled header)

**Comment by nickcole** [comment]
thanks!
