### ISSUE TITLE
QLinkedList is deprecated and Removed in QT6.

### ISSUE THREAD

**Issue by iatanasov77** [QxOrm/QxOrm#88]
QLinkedList is deprecated. This triggers many compiler warnings. Compiler suggest replace QLinkedList by std::list.

**Comment by QxOrm** [comment]
Hello,
If you download the latest source code from GitHub, you should not have any warning with QLinkedList and Qt6.
For example, see this file : https://github.com/QxOrm/QxOrm/blob/master/include/QxSerialize/Qt/QxSerialize_QLinkedList.h

**Comment by iatanasov77** [comment]
> Hello, If you download the latest source code from GitHub, you should not have any warning with QLinkedList and Qt6. For example, see this file : https://github.com/QxOrm/QxOrm/blob/master/include/QxSerialize/Qt/QxSerialize_QLinkedList.h

Thank you, Everything is okay , I didn't have the latest version.

**Comment by QxOrm** [comment]
Should be fixed if you download latest version of source code.
