### ISSUE TITLE
[LNK1169]default branch  Compile error 

### ISSUE THREAD

**Issue by ChaoII** [QxOrm/QxOrm#89]
Hi :
I have compiled on my macos x64 successfully（qt6.3.1）, but it make mistakes in my windows system。How can I solve the issue? Could you please  repeat the following questions？thanks very much.
             os:      windows11 x64
           cpu:      i7-12700
Qt version:      6.4.2
 compiler：     visual studio 2022
error detail:
```bash
E:\QxOrm\lib\QxOrm.dll : fatal error LNK1169: one or more multiple defined symbols founded [E:\QxOrm\build\QxOrm.vcxproj]
``` 
some pictures:
![image](https://user-images.githubusercontent.com/44053467/218403887-05072467-2d08-43fd-b1af-d2bf75e0461a.png)

**Comment by QxOrm** [comment]
Hello,
It seems that you have issues with generated mocs files.
I don't know how to help you, you should have an issue on your dev environment (Qt install, or cmake install or msvc install or whatever).

**Comment by ChaoII** [comment]
> Hello, It seems that you have issues with generated mocs files. I don't know how to help you, you should have an issue on your dev environment (Qt install, or cmake install or msvc install or whatever).

Thank you very much. I will check and replace qt and vs of different versions respectively. It will notify you as soon as I get the result.

**Comment by ChaoII** [comment]
I try to use other computer, but the problem is still existing.    V_V  
![image](https://user-images.githubusercontent.com/44053467/218499459-2b48ae56-746f-49ac-b14d-0d310d4108d4.png)
All errors is complain the  QxSingletonInit.obj (who has defined in this obj)

**Comment by QxOrm** [comment]
Should be fixed if you download latest version of source code.
