### ISSUE TITLE
QxOrm compile fail in Qt6.4.0

### ISSUE THREAD

**Issue by ivei** [QxOrm/QxOrm#91]
Hi :
I have compiled the master branch on my pc(win11) on Qt 5.15.2(visual studio 2019), but it make mistakes when I complie on Qt6.4.0 on visual studio 2019. 。How can I solve the issue? Thanks very much.
os: windows11 x64
cpu: i7-12900
Qt version: 6.4.0 and 6.4.2
compiler： visual studio 2019
error detail:
compiler says a lot of symbols are redefined. for example. for example:

QxClassX.obj:-1: error: LNK2005: "protected: __cdecl qx::QxDataMemberX<class qx::trait::no_base_class_defined>::QxDataMemberX<class qx::trait::no_base_class_defined>(void)" (??0?$QxDataMemberX@Vno_base_class_defined@trait@qx@@@qx@@IEAA@XZ) are redefined in QxSingletonInit.obj.

QxClassX.obj:-1: error: LNK2005: "private: long __cdecl qx::QxDataMemberX<class qx::trait::no_base_class_defined>::count_WithDaoStrategy_Helper(void)const " (?count_WithDaoStrategy_Helper@?$QxDataMemberX@Vno_base_class_defined@trait@qx@@@qx@@AEBAJXZ) are redefined i QxSingletonInit.obj 

and so on...

**Comment by QxOrm** [comment]
Hello,

QxOrm library should work with Qt 6.4, I think you have something wrong on your dev environment.
You should try a full rebuild of QxOrm and your project.

**Comment by QxOrm** [comment]
Should be fixed if you download latest version of source code.
