### ISSUE TITLE
How to modify the table name of the registered class binding when using it

### ISSUE THREAD

**Issue by xiaocai123123** [QxOrm/QxOrm#93]
The code is like below：

static const QString CylinderTableInfo_TableName = "CylinderTable1";
static const QString CylinderTableInfo_CylinderTableIdx = "cylinderTableIdx";
static const QString CylinderTableInfo_CylinderName = "cylinderName";
static const QString CylinderTableInfo_Note = "note";
struct CylinderTableInfo
{
	long cylinderTableIdx;
	QString cylinderName;
	QString note;
};
QX_REGISTER_HPP_QX_BASEMODULE(CylinderTableInfo, qx::trait::no_base_class_defined, 0)

QX_REGISTER_CPP_QX_BASEMODULE(CylinderTableInfo)
namespace qx {
	template <> void register_class(QxClass<CylinderTableInfo>& t)
	{
		t.setName(CylinderTableInfo_TableName);
		t.id(&CylinderTableInfo::cylinderTableIdx, CylinderTableInfo_CylinderTableIdx);
		t.data(&CylinderTableInfo::cylinderName, CylinderTableInfo_CylinderName);
		t.data(&CylinderTableInfo::note, CylinderTableInfo_Note);
	}
}

There are multiple tables with the same field in the database. The table names are CylinderTable1, CylinderTable2, CylinderTable3, etc. CylinderTableInfo uses the function setName to bind the table name "CylinderTable1" when registering. How to dynamically modify the class CylinderTableInfo when it is used, and bind it to other tables like CylinderTable2 or CylinderTable3

**Comment by QxOrm** [comment]
Hello,

To change the table name dynamically, you could try : 
`qx::QxClassX::getClass("CylinderTableInfo")->setName("CylinderTable1");`

But I think this is better to have CylinderTableInfo as a base class, then create CylinderTable1, CylinderTable2, CylinderTable3, etc... sub-classes which inherits from CylinderTableInfo.

**Comment by xiaocai123123** [comment]
Thank you so much for helping me solve this problem. 
Maybe I have too many tables with the same fields in my database to use the inheritance you describe，so i can`t use your recommendation.
I'm a big fan of yours，haha

**Comment by xiaocai123123** [comment]
Something goes wrong!
Only one table can be bind to a class.
 Use `qx::dao::save ` add table "CylinderTable1" one row 
 Then `qx::QxClassX::getClass("CylinderTableInfo")->setName("CylinderTable2")`   change the class to bind to table "CylinderTable2" 
Then use `qx::dao::save` , it always add  table "CylinderTable1" `s row not table "CylinderTable2"

**Comment by QxOrm** [comment]
This is because QxOrm library is not designed for that :(
I think the problem is that there is an internal cache which stores SQL queries based on a class.
This cache is used to improve performance, and to not have to rebuild the same SQL queries each time.

1 thing you could try, file ./src/QxDao/IxSqlQueryBuilder.cpp, method setSqlQuery, comment line 178 (to avoid to put SQL in the cache) : 
`IxSqlQueryBuilderImpl::m_lstSqlQuery.insert(key, sql);`
