### ISSUE TITLE
How can i use registed class in the namespace，it generates compilation errors

### ISSUE THREAD

**Issue by xiaocai123123** [QxOrm/QxOrm#95]
For example.Because it's registered in the namespace who name is test. This code will report errors. how to use registed class in a namespace.
namepace test
{
    static const QString CylinderTableInfo_TableName = "CylinderTable1";
    static const QString CylinderTableInfo_CylinderTableIdx = "cylinderTableIdx";
    static const QString CylinderTableInfo_CylinderName = "cylinderName";
    static const QString CylinderTableInfo_Note = "note";
    struct CylinderTableInfo
    {
        long cylinderTableIdx;
        QString cylinderName;
        QString note;
     };
    QX_REGISTER_HPP_QX_BASEMODULE(CylinderTableInfo, qx::trait::no_base_class_defined, 0)

    QX_REGISTER_CPP_QX_BASEMODULE(CylinderTableInfo)
    namespace qx {
    template <> void register_class(QxClass& t)
    {
        t.setName(CylinderTableInfo_TableName);
        t.id(&CylinderTableInfo::cylinderTableIdx, CylinderTableInfo_CylinderTableIdx);
        t.data(&CylinderTableInfo::cylinderName, CylinderTableInfo_CylinderName);
        t.data(&CylinderTableInfo::note, CylinderTableInfo_Note);
    }
    }
}

**Comment by QxOrm** [comment]
Hello, for this kind of issue, I would recommend to try QxEntityEditor application.
With this application, you will see how to define your C++ classes inside namespace (or other how to questions about how to write C++ class for QxOrm).
The documentation for QxEntityEditor application is available here : https://www.qxorm.com/qxorm_en/manual_qxee.html

**Comment by xiaocai123123** [comment]
Perfect！
