### ISSUE TITLE
NEXT MAJOR RELEASE

### ISSUE THREAD

**Issue by awesomeerictech** [QxOrm/QxOrm#97]
When are you planning to release Qxorm 1.4.9 ?

**Comment by QxOrm** [comment]
Hello, I expected to release it last year but didn't find the time to do it.
And now that Qt 6.5 just released, I would like to test if everything is working fine with this version before releasing it.
Anyway, QxOrm 1.4.9 will be very close (mabe exactly the same) as the latest version of source code currently available on GitHub.

**Comment by QxOrm** [comment]
Hello,
QxOrm 1.4.9 has been released :  https://github.com/QxOrm/QxOrm/releases
